### ISSUE TITLE
Glitch when trying to edit filtered observations in UI

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#1025]
When trying to change cell contents in a filtered search, the final row of observations disappears up into the column headers when you make the cell active and try to edit. This seems to consistently happen only with the last row of a filtered search. See below pic:

![image](https://user-images.githubusercontent.com/50387396/169741546-7c448788-6786-4aea-b518-1a05d625aa54.png)

**Comment by nspool** [comment]
@atcooper1 this should now be fixed in production.
