### ISSUE TITLE
Data portal endpoints displaying characters instead of accents in "area" and "site_name"

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#1026]
Some "areas" and "site_names" are displaying incorrectly in the Survey_list_public and site_list_public endpoints when downloaded from the AODN Portal. See below for exampleas

country	area    	        location	                               site_code	     site_name
Spain	Mï¿½ï¿½laga	Mediterranean (north west)	AND11	Cala del Peï¿½ï¿½on
Spain	Mï¿½ï¿½laga	Mediterranean (north west)	AND12	El dï¿½ï¿½ez
Spain	Mï¿½ï¿½laga	Mediterranean (north west)	AND39	El Rincï¿½ï¿½n
Spain	Mï¿½ï¿½laga	Mediterranean (north west)	AND42	La Rï¿½ï¿½bita
Spain	Mï¿½ï¿½laga	Mediterranean (north west)	AND43	Baï¿½ï¿½os de Guarda Viejas II
Spain	Mï¿½ï¿½laga	Mediterranean (north west)	AND47	Zacatï¿½ï¿½n
Spain	Mï¿½ï¿½laga	Mediterranean (north west)	AND49	La caleta de Salobreï¿½ï¿½a
Spain	Mï¿½ï¿½laga	Mediterranean (north west)	AND64	Isla San Andrï¿½ï¿½s (Parque Natural)

[Area and site names with characters.xlsx](https://github.com/aodn/nrmn-application/files/8751441/Area.and.site.names.with.characters.xlsx)

**Comment by bpasquer** [comment]
RESOLVED:
the encoding of character in the Talend tFileInputDelimited component was defaulted to "US-ASCII". Changed it to UTF-8.
See for example, the display of area 'Malaga' in the production database:

| site_code | site_name                         | country | area   |
|-----------|-----------------------------------|---------|--------|
| AND57     | Isla de Tarifa (Parque Natural I) | Spain   | Málaga |

and in the AODN portal :
![Screenshot from 2022-12-21 09-45-38](https://user-images.githubusercontent.com/3733612/208782498-e696a7f5-526c-41a0-8da1-a3432f77154a.png)
