### ISSUE TITLE
Scroll bar in the Jobs page

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#1040]
Is it possible to get a scroll bar in the 'jobs' page please? Just tried to check the ingested sheets, but the page cuts the list off and there is no way to scroll down to see the full list?

**Comment by nspool** [comment]
@atcooper1 which browser are you using? The scroll bar should be appearing on the right-hand side in Chrome:
![2022-05-24-120812_1272x928_scrot](https://user-images.githubusercontent.com/25042597/169934109-a30308cb-8cee-4b79-aed7-46fa38d214f4.png)

**Comment by atcooper1** [comment]
Weird, I'm using Chrome. I'll try refreshing my browser and cache. Thanks!
