### ISSUE TITLE
ATRC Ingest Validation "Survey group incomplete" should be warning not blocking 

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#1076]
We have staged some data (job 60) that is best ingested as ATRC because it has in situ quadrat data, but the data collection does not follow ATRC protocol for survey group (4 transects in a row distinguished by decimal depth).
Having confirmed with Toni, we both agree that the survey group should be non-compulsory (esp. in the interim before we can add more programs to separate data requirements).  Therefore the ingest validation "Survey group incomplete" which applies to ATRC data should be a warning not blocking. 

@nspool @bpasquer

**Comment by bpasquer** [comment]
I have amended the validation checks document :+1:

**Comment by LizziOh** [comment]
checked in systest, working
