### ISSUE TITLE
Bulk Species Update feature

### ISSUE THREAD

**Issue by nspool** [aodn/nrmn-application#1083]
## Description
Add a page to bulk correct observed species, given a date range and bounding-box location.

## Backlog Items

2. https://github.com/aodn/backlog/issues/4140

**Comment by nspool** [comment]
Just updated SysTest to version 11.0 (694) with the Bulk Species Update feature.

- Can be accessed from the "Correct Surveys" menu option
- Filter by Date Range and Location, State, Country or Species. _Bounding Box filter is not yet finished, so currently appears disabled._
- Selecting a species will display a pane containing the selected species, an autocomplete for the new species and a list of all the surveys that will be changed.
- Submitting the correction will create a corrections job, linked to from the correction pane after submission.
- Also note that since species corrections jobs aren't validated against a specific program, the Job program will appear as "None"

As always, please leave a note with any problems or feedback.

**Comment by LizziOh** [comment]
I've tested some examples of this feature.  It's great that the correction job is retained and viewable in the jobs list.

Sometimes functionality is a tad glitchy:
-  when doing multiple corrections, changing a species in the species filter and pressing search often returns all species (and takes a while to load).  Eventually it loads the chosen species after a few times or clearing the box and selecting again from the list.  
- after changing the species search and selecting a new species to correct, it would be good if the "correct to" box clears in order to avoid accidents.

Sometimes use cases are tricky and it is difficult to pinpoint the surveys to correct.  
- Often it requires a combination of state and one location, which can be executed separately however it would be good to have additional information to cross check the selected surveys.  For example, the use case to change species records : "Australian records west of Torres Strait (NT, WA and Mornington Island in QLD)".  I first changed WA and NT records, however to select the records on Carpentaria side of Queensland it would be good to cross check the locations of some surveys if desired.  If you open up the survey details page, it would be good to show the site_code and the site lat and longitude (as well as survey lat and long) so they can be plotted and checked.
- I think the bounding box will help with some required corrections, but also perhaps eco-region, as some examples from our errors list may need both, eg. use case "change all Atlantic ocean and Mediterranean records". Then if the UI showed the locations with the selected ecoregion or box or state (similar to the template generation functionality) it would be handy.  Perhaps this could be on the right side above the list of surveys ?
- I'm unsure how to correct the use case "change all records except Red sea".  if locations and surveys that are returned on the right side after a search could be deselected this would be ideal.

**Comment by nspool** [comment]
SysTest has been updated to 11.0 (701) with the Bounding Box filter. 

> when doing multiple corrections, changing a species in the species filter and pressing search often returns all species (and takes a while to load). Eventually it loads the chosen species after a few times or clearing the box and selecting again from the list.

This glitch should now be resolved. Also the search will also only enable if at least one other filter is selected with the time range.

> If you open up the survey details page, it would be good to show the site_code and the site lat and longitude (as well as survey lat and long) so they can be plotted and checked.

I've also added the  the Site lat & long to the Survey View page.

> I'm unsure how to correct the use case "change all records except Red sea". if locations and surveys that are returned on the right side after a search could be deselected this would be ideal.

A solution may be to change all records and then change the Red sea records back to the original.

> Then if the UI showed the locations with the selected ecoregion or box or state (similar to the template generation functionality) it would be handy. Perhaps this could be on the right side above the list of surveys ?

Would adding the ecoregion filter and displaying the locations for the selected ecoregion be sufficient?

**Comment by nspool** [comment]
SysTest has been updated to 11.0 (705) with the Eco Region filter, with the associated locations displaying on the right-hand side.

Please leave a note if you encounter and problems or have feedback.

**Comment by LizziOh** [comment]
> SysTest has been updated to 11.0 (701) with the Bounding Box filter.
> 
Thank you , I will test this soon. @atcooper1 perhaps you'd like to test this one as well?

> > when doing multiple corrections, changing a species in the species filter and pressing search often returns all species (and takes a while to load). Eventually it loads the chosen species after a few times or clearing the box and selecting again from the list.
> 
> This glitch should now be resolved. Also the search will also only enable if at least one other filter is selected with the time range.
> 
Yes this fix works well now.

> > If you open up the survey details page, it would be good to show the site_code and the site lat and longitude (as well as survey lat and long) so they can be plotted and checked.
> 
> I've also added the the Site lat & long to the Survey View page.
> 
Thank you! Is it possible to add site_code as well?

> > I'm unsure how to correct the use case "change all records except Red sea". if locations and surveys that are returned on the right side after a search could be deselected this would be ideal.
> 
> A solution may be to change all records and then change the Red sea records back to the original.
> 
Not exactly.  If the Red Sea records contain a mixture of legitimate records to the species to be changed and the new species this would introduce errors when we just required these records to be untouched.  ie. if we changed all the records to the new species then changed all of that species back tot the original we would lose the split of species.

> > Then if the UI showed the locations with the selected ecoregion or box or state (similar to the template generation functionality) it would be handy. Perhaps this could be on the right side above the list of surveys ?
> 
> Would adding the ecoregion filter and displaying the locations for the selected ecoregion be sufficient?

It would be handy to have the locations appear for any chosen filter (eg. just filtering for all records of a species) and then be able to de-select locations or surveys.  However if this is problematic perhaps we can discuss the best options.

**Comment by atcooper1** [comment]
Testing bulk species correction:

When selecting an area to bulk-change a species, it would be great if the search could act more like the template generator (i.e. need to be able to add multiple areas/states/locations/ecoregions and need to be able to remove Locations from an Area search, and remove surveys from a Location search, etc. 

Can the dates please be auto set to the first survey date (i.e. 01-01-96) and the current date

Is it possible to please get the survey output to be heirachical? I.e. Display all surveys under Area/State --> Location --> surveys so we can visualize the output easier? 

Can all-filtered parameters please display a list of Locations in the output?  (i.e. using State/Area filter shows a list of Locations, but using the bounding box doesn't)

Testing the bounding box feature:
- if you have another filter active (i.e. an Area/State selected) the output will give you surveys for the bounding box, but locations for the State/Area selected. 
- Is it possible to have a 4 point box, to account for non-square shapes? the current min/max is tricky to use and is hard to capture the area we are trying to mimic

**Comment by atcooper1** [comment]
Correct species - When you select a species, then select a Location/Area - the species disappears. User needs to go back and re-type species every time you add values to the filters before searching. 

Unable to "go back" - i.e. If the user selects "search" but needs to modify the results, there is no way to go back to the "Correct Species" page - user needs to select it again from the side tab.

Seems to be a glitch with the "Correct to" field - user must select the species 2-3 times before the "submit correction" button becomes live. Text either disappears and user needs to re-enter the name, or the 'submit correction' button stays greyed out

**Comment by bpasquer** [comment]
@atcooper1 
1) I couldn't reproduce the disappearance of the species name on systest 
2) The  box containing the search filters collapses you press search. You can bring it back up  by pressing on the  arrow ^ on the right hand side of the screen
![Screenshot from 2022-12-16 11-03-55](https://user-images.githubusercontent.com/3733612/207992408-51a08439-74e5-40b0-a3cb-71a259920e41.png)
3) I can't reproduce the glichty behaviour, sorry

**Comment by atcooper1** [comment]
Hi @bpasquer no the text was disappearing from the text box on the screen before the one you have above. As soon as i was clicking on another field (i.e. Location, Area, etc) the species name was disappearing, however it just worked ok, when i tried then? I'll see if i can replicate it and capture it for you

**Comment by bpasquer** [comment]
Fro the record, from email exchange 19/12:
From Bene:
>Nathan had a look at the video and wanted to know whether you are pasting in the text box, instead of selecting from the drop-down menu. 
The UI expects a selection from the drop down and would therefore exclude and delete free text input like you might have been doing 

Toni's reply:

>Yes, If I paste in text, then the drop-down doesn’t appear, as you say and I assumed it needed to be selected, but even when I free text (or try and paste a portion of the name to ensure correct spelling), half the time the drop down doesn’t appear? The issue is the same with the kml file. If I select it and add it to the UI it disappears after I’ve loaded it. It’s as if the UI needs to recognise it and can add it to a pseudo “drop down” menu for selection - so I have to select everything twice…if that makes sense?

**Comment by LizziOh** [comment]
Could we please have the pre-set "Start Date" filter to 01/01/1992?  This tripped me up when testing a bulk species change.  The earliest surveys in the database are from 1992 not 1996
