### ISSUE TITLE
WoRMS search functionality ineffective

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#1092]
WoRMS search functionality is returning a server error when user searches for a species name (Genus + species). The search returns results when entering a genus only, however this does not consistently return all genus search results for a species. And in some cases, returned searches are showing duplicated results (i.e. same accepted species name with same taxonomic information)
e.g.
![image](https://user-images.githubusercontent.com/50387396/177239009-aaccafac-e054-419c-89bf-8b98534ee8e7.png)

**Comment by bpasquer** [comment]
Duplicate results are returned for exact match only
