### ISSUE TITLE
Species Phacelocarpus apodus will not ingest even though it is in the database

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#1166]
eg. job: https://nrmn.aodn.org.au/data/job/126/edit

throws a species does not exist error, but the spelling is identical to an existing observable item/species - for which i've checked for trailing spaces in the species fields etc.

**Comment by nspool** [comment]
Should be fixed after reindexing the `observable_item_ref` table. Please try ingesting this sheet again.

**Comment by LizziOh** [comment]
this is fixed now, thanks
