### ISSUE TITLE
Deleting/changing superseded by not working

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#1202]
Unable to remove a superseded by species name and replace it with a valid name from the observable items list.

**Comment by nspool** [comment]
@atcooper1 which record are you editing and what are you trying to change the name to?

**Comment by atcooper1** [comment]
E.g. Cromileptes altivelis - trying to remove the 'Superseded by' species (Chromileptes altivelis) so i can reverse the superseding (i.e. supersede Chromileptes with Cromileptes) but because i can't delete the exiting superseded buy species, i am unable to assign the correct name as it's already superseded.

**Comment by atcooper1** [comment]
I can confirm I am able to:
- remove a superseded species from an observable item ( I am yet to confirm if this change is accurately reflected in the Verification stack - i waited 30 mins and wasn't able to see the update, but will try again tomorrow in case the materialised views take longer to refresh in Verification).
- supersede an active observable item by adding a species to the 'superseded by' drop down menu

However it seems i am also able to supersede a species with itself (i can select this from the drop down menu). This is problematic for circular referencing.
![image](https://user-images.githubusercontent.com/50387396/218655315-a6843a84-a1b4-4c1d-9fa8-fdf137234c00.png)
![image](https://user-images.githubusercontent.com/50387396/218655628-6779b889-a779-48ed-ae0b-efe01346f1b8.png)

**Comment by LizziOh** [comment]
I have also tested this and find it to work well except for being able to supersede an obs item by its own name when the "superseded by" field is empty.  Note that this is not consistent - it does not happen if trying to change an already populated "superseded by" field, as in the below example where i attempted to change it from Sargassum sonderi to itself (Sonderopelta coriacea).  Note the blocking feed back is a bit misleading though as it the species does exist in the db and is valid.
![image](https://user-images.githubusercontent.com/52521522/218873549-b765cdbc-dc2a-406e-aee7-4a976fb1cee5.png)

**Comment by vfisaac** [comment]
Fix implemented to prevent Superseded by field being populated with the Species name of the record you are editing. Available now in Verification for you to test
