### ISSUE TITLE
Private endpoint shared links

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#1224]
Data officer can create a shared link for selected private endpoint from a new screen in the UI.
Shared links are diplayed in a table, with sorting enabled.
Multiple links can be created at once
Links have an expiry date, and are deleted form the list automatically after expiry
Link are refreshed every night

**Comment by LizziOh** [comment]
Great feature. I think that the copy button is not working though?

**Comment by nspool** [comment]
The copy button will work in production, just not in verification because we don't have https enabled on that site.

**Comment by atcooper1** [comment]
This is great, thanks all.
Just been checking the views and wanted to clarify whether the UI endpoint links are being generated from Prod, rather than Verification? Currently the num rows are differing between the downloadable endpoints via the UI and what I can see in verification (via pgadmin), so just wanted to confirm this before I dig deeper into testing? Thanks!

**Comment by nspool** [comment]
@atcooper1 the endpoints are being generated from the verification database once per day (at around midnight) so if no changes have been made they should match.

**Comment by atcooper1** [comment]
Hmmm.. weird. So for South Australia (as a sub-set example), I get 90693 rows from the UI endpoint download (and from Prod), but I get 89967 from Verification? The missing 727 rows all seem to be data from 2022 surveys loaded before Christmas?

**Comment by nspool** [comment]
@atcooper1 the verification db was restored from an older backup. We will organise a time to take it down and restore from the latest production backup instead.

**Comment by LizziOh** [comment]
It does seem that the csv links provide more data than expected rather than less though, suggesting they are generated from production? for the ep_m1_all endpoint the row numbers are:

Verification db (accessed thorough PGAdmin): 1541497
Prod (accessed thorough PGAdmin): 1543746
Csv link downloaded: 1543746

**Comment by bpasquer** [comment]
@LizziOh  Checked today :
The row number of data in ep_m1 in the verification DB (1543746) match the row numbers in Prod and in the csv extract.

**Comment by nspool** [comment]
I think the verification CSV files were sometimes being overwritten by another test app running on an older database. 

I've created a new S3 bucket just for verification and regenerated the CSVs. Please try it out again.

**Comment by atcooper1** [comment]
Hi @nspool i'm unable to access Verification UI - has it been shut down for the weekend?

**Comment by nspool** [comment]
Hi @atcooper1 the verification portal has been running and is accessible to me. Is the UI showing an error?

**Comment by atcooper1** [comment]
I'm getting an "Unauthorized" error message when I try and log in to Verification using info@aodn.org.au

**Comment by nspool** [comment]
@atcooper1 can you try with your same username and password as production?

**Comment by atcooper1** [comment]
Ok, yes, Verification is working with Prod usernames and passwords. @LizziOh tagging so you are aware of this change. Thanks Nathan

**Comment by LizziOh** [comment]
> Ok, yes, Verification is working with Prod usernames and passwords. @LizziOh tagging so you are aware of this change. Thanks Nathan

Thanks for the information.  I'm not having success logging in with either of these usernames/passwords currently

**Comment by atcooper1** [comment]
@nspool I can confirm that I have been able to download available endpoints successfully using the links in the Verification UI and the views match what is currently in Verification DB.
NB: I think Lizzie mentioned this, but the 'Copy link' feature is not working

**Comment by nspool** [comment]
Thanks @atcooper1. Unfortunately the copy button won't work in verification because we don't have https enabled. It will work in production.
