### ISSUE TITLE
Update length-weight biomass coefficient with values from Fishbase 

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#1233]
Follow up on https://github.com/aodn/backlog/issues/4644

Dump of data retrieved from github : [https://github.com/ropensci/rfishbase/tree/master/parquet/fb_parquet_2021-06](https://github.com/ropensci/rfishbase/tree/master/parquet/fb_parquet_2021-06)

After checking multiple values, it appears that there are some discrepancies in the value of A's and B's as compared to what is displayed on the [Fishbase website](https://fishbase.se/search.php), which suggest the dump is not be the most recent version of the data 

The resulting file of Fishbase LW data mapped to NRMN observable item :
[Mapped_FishBase_LW.csv](https://github.com/aodn/nrmn-application/files/10620239/Mapped_FishBase_LW.csv)

@atcooper1 @LizziOh 
Please inspect the data and let us know if we can use this material to run a bulk update .

**Comment by atcooper1** [comment]
Thanks @bpasquer - have circulated to RSS, GE and NB for comment/confirmation and will advise whether they are happy to move forward with FB values as soon as i hear back.

**Comment by atcooper1** [comment]
Hi @bpasquer, thanks for progressing with these! The A's and B's are quite different as you say, but this might be ok due to the way biomass is calculated. We were wondering if it would be possible at all to run these new Fishbase a's and b's against a tropical and temperate location (i.e. Encounter and GBR- North) so I can compare these against our current values and see how these will affect the biomass calculations? I think everyone will agree to move forward with the Fishbase values, but it would be good to check this on a small sub-set to ensure we aren't creating more issues.

**Comment by bpasquer** [comment]
Yes sure @atcooper1, understanding the impact of the change  is a very reasonable request.

**Comment by atcooper1** [comment]
Hi @bpasquer I've taken a look at the biomass values and the FB values generally look better, but there are a few funky things I've noticed (e.g. the leatherjacket values seem out). Can I confirm whether these biomass calculations include the diver bias calculation that is applied to the existing biomass values?

**Comment by bpasquer** [comment]
yes, the biomass calculations are done using the same code as the current calculation, and include use the diver bias rule

**Comment by bpasquer** [comment]
The table below compares a and b values before(in prod replica) and after(in verification) the Fishbase update
Some value do change a fair bit with  biomass calculation result that can almost double 

| obsrvable_item_id | observable_item_name | common_name | New a (in verification) | Old a (in prod replica) | New b (in verification) | Old b (in prod replica) |
|---|---|---|---|---|---|---|
| 2440 | Cantherhines fronticinctus | Spectacled Leatherjacket | 0.021379599347711 | 0.0561 | 2.92000007629395 | 2.653 |
| 2441 | Cantherhines dumerilii | Barred Leatherjacket | 0.025118900462985 | 0.0561 | 2.92000007629395 | 2.653 |
| 2442 | Cantheschenia grandisquamis | Largescale Leatherjacket | 0.021379599347711 | 0.0256 | 2.92000007629395 | 2.7 |
| 2443 | Cantheschenia longipinnis | Smoothspine Leatherjacket | 0.009999999776483 | 0.0684 | 3.03999996185303 | 2.563 |
| 2444 | Paraluteres prionurus | Blacksaddle Filefish | 0.021379599347711 | 0.0256 | 2.92000007629395 | 2.7 |
| 2445 | Pervagor alternans | Yelloweye Leatherjacket | 0.021379599347711 | 0.025 | 2.92000007629395 | 2.946 |
| 2446 | Pervagor janthinosoma | Gillblotch Leatherjacket | 0.02089300006628 | 0.025 | 2.92000007629395 | 2.946 |
| 4423 | Pervagor aspricaudus | Orangetail Leatherjacket | 0.021379599347711 | 0.025 | 2.92000007629395 | 2.946 |
| 4910 | Pervagor melanocephalus | Blackhead Leatherjacket | 0.021379599347711 | 0.025 | 2.92000007629395 | 2.946 |
|  |  |  |  |  |  |  |
