### ISSUE TITLE
Add Class Teleostei to valid method 1 species

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#1246]
It looks like WoRMS has done another taxonomic update and Actinopteri is now listed as a Superclass and Teleostei is the new Class of ray-finned fishes. Can we please as Teleostei to the list of accepted Classes for valid Method 1 species?

**Comment by bpasquer** [comment]
Yes I will make a combined update for Actinopteri(https://github.com/aodn/nrmn-application/issues/1129) and Teleostei
