### ISSUE TITLE
Cut paste functionality not working as expected

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#1275]
While correcting observational records, the Cut function works, but the paste and copy function is not working. Presumably this has something to do with the changes to the within-cell arrow toggling, but this is making data corrections difficult when needing to batch-move a lump of sized individuals to different columns.

## Notes:
1. It looks like this PR is causing the problem, a bug in the checking (https://github.com/aodn/nrmn-application/pull/1258)

## PR @craigrose 
1. https://github.com/aodn/nrmn-application/pull/1309
2. https://github.com/aodn/nrmn-application/pull/1311 (replaced 1309)

## DOD @vietnguyengit

**Comment by bpasquer** [comment]
Confirmed in Edge: none of the Cut, Copy or Paste function work

**Comment by bpasquer** [comment]
Pasting still not working

**Comment by atcooper1** [comment]
In addition, Users are now unable to select/copy rows from the UI and paste them into email/excel. Previously users could select rows (usually with issues) directly from the UI grid and paste the values into an email (for example) to resolve data issues. Now this is not possible, even if the User manually highlights the cells, there is no copy functionality - only delete.

**Comment by LizziOh** [comment]
Fix applied in systest has been tested and is working

**Comment by vietnguyengit** [comment]
DoDed
