### ISSUE TITLE
Gateway timeout error on data ingest

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#1276]
On data ingest, screen returns a Gateway Timeout error. UI is unusable for ~5 mins (returns a "Server busy" error on attempt to refresh). The UI then takes you back to the working sheet, however on further "save and validate", the UI returns a list of new validation errors ("Surveys exist"). When user goes back to jobs list, the job that "failed" the ingest has disappeared and seems to have loaded (albeit without ingest feedback).

![image](https://github.com/aodn/nrmn-application/assets/50387396/a3c7067e-e046-4517-8ea7-2d70f17aff46)

**Comment by bpasquer** [comment]
Reproduced in Edge witht Copy_of_USWC_combined_2022.xlsx (~1200 rows):
On ingest the server times out after submitting the sheet. The ingest summary is not provided but the sheet appears to have been  ingested successfully
