### ISSUE TITLE
Refreshing materialized view fails with "ERROR: value out of range: underflow"

### ISSUE THREAD

**Issue by craigrose** [aodn/nrmn-application#1313]
When trying to restore backup from `s3://imos-backups/backups/db1-prod-aws-syd.emii.org.au/pgsql/2023.08.30.00.07.35/nrmn_prod/nrmn.dump` the materialized view `nrmn.ep_rarity_range` fails to create (and refresh) with `ERROR: value out of range: underflow`.

As a result materialized views that depend on this one will also fail.

This will be a problem if we need to restore the backup.

**Comment by bpasquer** [comment]
Will check with @srw999 if it is still an issue

**Comment by srw999** [comment]
i believe this problem disappeared when we migrated to RDS - i certainly never saw it during the migration process when i was continually restoring nrmn databases to different environments.

**Comment by bpasquer** [comment]
OK thanks , will close the issue then
