### ISSUE TITLE
bug returned - filtering resets too fast when changing values in filtered field

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#1321]
If I filter for rows I want to change, then change the first value with the intention of copying the value down the column auto-refiltering occurs immediately upon changing the value and interrupts the process

**Comment by utas-raymondng** [comment]
@LizziOh can you tell me which screen you referring. it looks ok for filter on job list screen and correct survey screen

**Comment by bpasquer** [comment]
@utas-raymondng, I think the bug Lizzie that is back may be: https://github.com/aodn/nrmn-application/issues/690

**Comment by utas-raymondng** [comment]
Related -> https://github.com/aodn/nrmn-application/issues/1319
