### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#1322]
- Filtering in data staging page dubious.  not highlighting all records of a given vaildation error.  not filter all records of a given validation error either.  Eg, survey exists error.
- Clicking on any area of the top of the page (in the white space not on a button) exits page without saving
- - depth integer not displaying in survey info page on UI, eg. survey 923402443 is 8.3m depth but in survey info page it says 8.  https://nrmn.aodn.org.au/data/survey/923402443
- Trying to save and validate is inconsistent, sometimes failing sometimes not returning the summary page, and once returning two of it:
![image](https://github.com/aodn/nrmn-application/assets/52521522/0eb50862-a512-4194-b107-f2640732f240)

**Comment by utas-raymondng** [comment]
Can repeat in Edge: 
* Clicking on any area of the top of the page (in the white space not on a button) exits page without saving

Depth is always integer as store in database

![image](https://github.com/aodn/nrmn-application/assets/101624355/f4d278e3-5afb-4060-a7e3-4c773973a26a)

**Comment by bpasquer** [comment]
@utas-raymondng : the field `depth` in the View Survey page should actually show a one decimal number resulting from the combination of the depth and survey number.

**Comment by utas-raymondng** [comment]
https://github.com/aodn/backlog/issues/5177 ticket raised
