### ISSUE TITLE
bulk update - protection status of surveys from job 389 OR job roll back and re-ingest

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#1323]
I belatedly received protection status for all sites for the surveys uploaded in job 389.  Since the surveys were ingested prior to the protection status being added for the sites, they are wrong in the survey list.

Could we either bulk update the protection status and MPA information according to the current site status, or roll back this job and re-ingest  pleease?

**Comment by bpasquer** [comment]
@LizziOh we will bulk update the surveys

**Comment by LizziOh** [comment]
**Correction*** the job I am referring to is the ingested job number 393 (not 389)

**Comment by bpasquer** [comment]
PR to update survey status: 
https://github.com/aodn/nrmn-application/pull/1337

**Comment by bpasquer** [comment]
From Lizzie's email (2023-12-21)

> the survey protection status have been updated well .  Good to go!

Issue Resolved.
