### ISSUE TITLE
Default Time to 12:00 if it was not recorded

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#195]
Time is not always recorded in the ingested datasheets. In these cases, `survey_time` should default to 12:00 pm

**Comment by bpasquer** [comment]
From the following discussions with Toni and Lizzie, I think that Null entries in the Time column should be valid, and as a consequence, we don't need to default Time to an arbitrary value.  
***************
Bene, 15 March 2021
>Hi ,
Toni mentioned during the meeting that the survey “time” should default to 12:00 pm if the value was not recorded.
>Just want to check
>1 - if it applies to both RLS and ATRC  data
>2 - if we should backfill historical data : there is >16000 surveys (ATRC and RLS) with no recorded time.
Cheers,
Bene

Lizzie: 
>Hi Bene,
 From my perspective if an ATRC survey has no time then there’s no need to make an arbitrary one, as long as blanks are not an issue for the system, or from an RLS perspective. 
Cheers!
Lizzie

Toni:
>Hi Bene,
Are you able to advise whether “blanks” in the time column will be problematic, we might need to have a chat to Rick/Graham/Nev about the best way forward with this? If we are going to use time to enter night surveys moving forward, then we might need to think about how this is managed.
We have a meeting scheduled for Thursday or Friday, can we let you know then?
Cheers,
Toni
 
Bene:
Hi Toni , Lizzie,
 
>Blanks in the time column will not be problematic. 
Personally, now that I have looked at the data and seen so many surveys with no time recorded ( 57% ) and considering Lizzie response, I wonder if defaulting the time to an arbitrary value on ingest is really necessary.
Also, can you explain why managing the night surveys would be different from daytime surveys? 
Cheers,
Bene

Toni:
>Hi Bene,
I think you are right. If leaving them blank is acceptable, then this is probably the best way forward (providing it doesn’t cause formatting issues). 
(Historically times were given the default as blanks were problematic).
Thanks,
Toni

**Comment by ccmoloney** [comment]
Can we close this @bpasquer ?  Or do we need to verify that we currently support NULLs for times (and fix if we don't)?

**Comment by ccmoloney** [comment]
@bpasquer Bump

**Comment by bpasquer** [comment]
Can't confirm for sure it's been fixed but assuming so cause a missing Time value is not generating an error anymore. The default value is not appearing in the staged page( and doesn't need to really). 
 can you comment @utas-tajona
