### ISSUE TITLE
Flexibility to add columns to pivot tables 

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#237]
Many columns are unavailable to add to pivot table.
The system should provide the ability to add any column to the pivot.

**Comment by bpasquer** [comment]
For example: there is no way to check/summarize the size observation data by species because the sizes are unavailable in the pivot

**Comment by ccmoloney** [comment]
Allow pivoting of all columns (including size class columns)

**Comment by utas-tajona** [comment]
if they want more column it would be good to know which aggregation

**Comment by bpasquer** [comment]
They would like to see sums. 
A uses cases they described yesterday was: Add size classes to the pivot table to see if a diver is biased towards large size classes

**Comment by ccmoloney** [comment]
Should be low priority - we have implemented the Export to Excel feature to allow the data to be pivoted in whatever way is required in Excel.
