### ISSUE TITLE
Problems switching back between pivot and data view

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#238]
When switching back from pivot mode you have to reselect some missing columns (if you have added them to pivot).  They then do not display in each row properly.  They do not come back in the same column order, and then the data cannot be re-sorted back to original order using the ID column.  The sorting looks to be incorrect.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/2961)

**Comment by bpasquer** [comment]
Update:  Toggling between pivot mode and data mode glitches the display: 
When switching back to data view, column Vis, Method, Total, Inverts and the size class column have retain their values, all other columns are empty

**Comment by ccmoloney** [comment]
Discuss - export data to allow pivoting outside ag-grid

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234.
Also: we have implemented the Export as Excel feature to allow pivoting outside the editor (in Excel on the users computer)
