### ISSUE TITLE
Invert Sizing used on ingest row by row based on column 'Use InvertSizing'

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#239]
The "Use InvertSizing" column in the datasheet sets which size class to use to ingest the data (i.e. Fish or Invert size Class). The 'Use Invert Sizing" column is not displayed in the UI. This information is essential for ingest of the correct sizes,  as sometimes the values are edited as Yes or No for different reasons.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/2962)

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234

**Comment by LizziOh** [comment]
tested
