### ISSUE TITLE
Datasheet upload failing

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#240]
It seems like the system is unable to load data sheets that haven't already been ingested, and doesn't provide feedback as to why.

**Comment by utas-tajona** [comment]
could you please provide a link where it's happening or a file to reproduce it?
Thanks

**Comment by bpasquer** [comment]
This issue is based on Toni and Lizzie's feedbacks. I will ask Lizzie if she as an example to reproduce it

**Comment by bpasquer** [comment]
Better error reporting implemented
