### ISSUE TITLE
Add observable items search function

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#243]
Search function not fully functional:
Searching for "Ranella" in WoRMS, does not come up with _Ranella australasia_,  but does searching for "australasia".  
The NRMN search does not find _Ranella australasia_ at all

**Comment by jonescc** [comment]
Yes - its only currently returning 50 search results so that would be outside that range.

We need to add paging to show all results

**Comment by jonescc** [comment]
Wasn't possible to do that with previous WORMS api we used so it was missed.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/2960)

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234

**Comment by LizziOh** [comment]
tested
