### ISSUE TITLE
L5 and L95 columns formatting

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#247]
The column headers L5 and L95 in staged data with inverts sizing) are appearing in the same format as the size classes (in green with a red size class "1" underneath) See the image below and the attached file to reproduce the error)

![Screen Shot 2021-04-29 at 1 24 56 pm](https://user-images.githubusercontent.com/3733612/116498992-6d0a3380-a8ee-11eb-99c0-17c660057184.png)

[Scott's sites 2019 RLS TEMPLATE DEW.xlsx](https://github.com/aodn/nrmn-application/files/6396183/Scott.s.sites.2019.RLS.TEMPLATE.DEW.xlsx)

formatting for these columns should be 'normal' formatting i.e. not like the size class data

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/2958)

**Comment by bpasquer** [comment]
L5-l95 column not staged anymore
