### ISSUE TITLE
"Save"  behaviour is inconsistent

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#250]
Saves are a bit glitchy - sometimes changes are saved and others the screen goes blank and on refresh, all changes are lost.

**Comment by ccmoloney** [comment]
@bpasquer Can you reliably reproduce this?

**Comment by bpasquer** [comment]
No, not reliably @ccmoloney.  I've had the screen going blank sometimes but didn't notice a loss of changes

**Comment by ccmoloney** [comment]
I think we definitely need to make sure that any errors that happen during a save are displayed in some way on the UI & there is already a backlog item to make sure that we block on the UI until the save is completed in the backend.

**Comment by ccmoloney** [comment]
This issue has highlighted that we need to display error messages to the user when API calls result in errors.  I have raised a backlog item to resolve: https://github.com/aodn/backlog/issues/2965

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/2966)
