### ISSUE TITLE
Clicking on validation feedback no longer takes you first matching row

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#251]
Error feedback no longer shows the records in error when clicking on it and doesn't take you to the first matching row.

Noticed in v0.0.162

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/2963)

**Comment by ccmoloney** [comment]
Follow on: when you fix one/or more, the highlighting should show the next instance.

**Comment by utas-tajona** [comment]
fixing one or more need to be sent back to backend which mean save/validation. there is no mechanism to check if one validation has been updated

**Comment by bpasquer** [comment]
v 0.226 - Rows with error/warning are now correctly highlighted. I consider this issue resolved
