### ISSUE TITLE
Sitecodes must be unique

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#254]
Currently allows new sites with the same sitecodes as existing sites. 
SiteCodes must be unique within a location. Checks should be done to ensure the combination of  Sitecode/Sitename/Location is unique.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/2967)

**Comment by bpasquer** [comment]
resolved by https://github.com/aodn/nrmn-application/pull/317
