### ISSUE TITLE
Difficult to see what sitecode a location is up to

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#255]
Currently, sitecode is set to an "alphabetical" sort (i.e TAS1, TAS11, TAS12) but should default sitecode with a numerical sort (i.e. TAS1, TAS2, TAS3)

**Comment by ccmoloney** [comment]
Implement custom default ordering in API get operation.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3041)

**Comment by ccmoloney** [comment]
New default ordering implemented for Site List page which should resolve this.  Introduced in version 0.0.234

**Comment by LizziOh** [comment]
tested
