### ISSUE TITLE
Observable items should have a drop down list of "active" species under "superseded by"

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#257]
Currently, you can just type anything into "Superseded by".
Needs to only allow superseding of valid, current species names (species which haven't already been superseded) 
Should be using a lookup of valid acceptable species names for superseding (to avoid circular referencing).

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/2964)
