### ISSUE TITLE
ATRC survey complete check  incorrect

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#268]
ATRC surveys are defined by the combination of site/date/depth/survey_num.
Each ATRC surveys should have at least: 

- one record each on block 1 and block 2 for Method 1
- one record on block 1 for Method 2

In the following file, the surveys done at depths 5.3 and 5.4 are incomplete. 
Survey 5.3 is missing Method 1 Block 1
Survey 5.4 is missing Method 1 block 2 and Method 2 Block1

The following warning is raised:  [MIR-S10,5/04/2019,5.4] has incorrect set of methods: [1]

Warnings for missing 5.3 [M1 B1] and 5.4 [M1 B2] should have been raised too.

[ATRC_SurveyComplete.xlsx](https://github.com/aodn/nrmn-application/files/6431333/ATRC_SurveyComplete.xlsx)

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3024)

**Comment by ccmoloney** [comment]
Will be resolved in next release

**Comment by LizziOh** [comment]
tested
