### ISSUE TITLE
Species epithet display in New observable item view

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#294]
from feedback 0.0163: 
New Observatble Item - search WoRMS and select from list generates species epithet as whole species name (genus and species) rather than just species. 
Ex:  the species epithet of _'Haliotis elegans'_  is _'elegans'_

Species epithet should display just 'species' name if one exists.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3025)
