### ISSUE TITLE
Validation check fails to find records with no data 

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#297]
from 0.0190 
Validations: fail to find empty records, (rows with only zeros, no observations).  Only finds formatting errors (ie. if total is blank, not zero)
Empty records should be picked up by the "Record has no data and but not flagged as ‘Survey Not Done’ or “No Species Found” " check

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3027)

**Comment by LizziOh** [comment]
tested
