### ISSUE TITLE
RLS Depth allows more than one decimal

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#298]
Depth should have no more than one digit in the decimal place.
ATRC depth with 2 digits is  raised as invalid but RLS depth with 2 digits in the decimal place is allowed 

Check on RLS depth with 2 decimal digit should raise an error

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3028)

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234
