### ISSUE TITLE
Incorrect error message for ATRC block validation

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#302]
v0.0190 
ATRC Invalid block validation says block can only be 0,1,2 or 10. 
Valid ATRC block value can be 0,1 or 2.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3030)

**Comment by ccmoloney** [comment]
Will be included in the next release.
