### ISSUE TITLE
Observable item species lookup view incomplete

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#304]
The list of matching records of the species lookup provides taxonomic information only.
Superseding information is not available in the view.
Currently, an error is raised when selecting a superseded species, and the species is no longer available for selection.

The superseding information should be visible in the species lookup view.

**Comment by bpasquer** [comment]
linked to https://github.com/aodn/backlog/issues/3021

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234
