### ISSUE TITLE
Site List view : Latitude/longitude coordinate precision rounded to 5 decimal 

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#305]
Site coordinates are stored in the database with a 4 to 6 decimal precision.
Some records in the List Site view display coordinate precision inconsistent with the data stored in the database.
These records show latitude and longitude with 16 decimals.

Values of site Lat/Lon values displayed in the List Site view should be the same (with the same precision) as the value stored in the database.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3032)
