### ISSUE TITLE
Find and Replace on selected columns or selected region

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#307]
v0.0190
Find and replace defaults to the entire document.

The ability to selected columns to perform a Find and Replace or to find/replace in a selected region of cells would be useful to user.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3178)

**Comment by LizziOh** [comment]
This is working, it is a bit unclear to the user which column is selected.  you have to assume it works off the column which has a cell highlighted, because we are unable to select/highlight columns in the UI.  - but that may be a separate issue.
