### ISSUE TITLE
Diver name valid for Buddy and PQs

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#308]
v0.0190
Diver name AND initials should be accepted in Diver, Buddy and PQs columns.
However,currently Buddy only allows for Initials , even on valid, exisiting divers

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3033)

**Comment by LizziOh** [comment]
This works except for full diver names with accents... if they are stored in the database with and accent, eg. 
![image](https://user-images.githubusercontent.com/52521522/131622763-b79778e2-33a3-4a76-90b4-e2038b7eaf72.png)
then the plain text version in the staged data is not recognised.  Is this an issue @atcooper1 ?

**Comment by atcooper1** [comment]
All RLS divers from Spain have accents as well so this will be problematic. In the past there haven't been checks on Buddy, but Diver names with accents were previously accepted with OR without the accent. Perhaps Just created an Alias to allow for names that may come in as plain text or with accents? The alternative solution is for the Data User to use initials only for accented names?

**Comment by bpasquer** [comment]
the check will ignore the accents by comparing name in ascii format

**Comment by LizziOh** [comment]
I have checked this in systest now and both initials and names with/without the accents are correctly handled on ingest.
