### ISSUE TITLE
Remove validation checks on species Common Name

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#312]
Feedback from users:

"Checks are not needed on common name as these aren't stored - these are purely for volunteers to cross-check the entries. Currently validation checks prevent '0' in the Common name column, but these shouldn't matter."

## Tasks
- [ ] Remove validation checks on Common Name column
- [ ] DOD

**Comment by utas-tajona** [comment]
Again very strange.... There is currently no validation on common name

**Comment by utas-tajona** [comment]
![Screenshot from 2021-05-20 11-08-38](https://user-images.githubusercontent.com/67612124/118903876-fea01a80-b95b-11eb-8ff1-9603c1e060ed.png)

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234

**Comment by LizziOh** [comment]
tested
