### ISSUE TITLE
Use arrows to navigate in grid when editing cell values

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#315]
Feedback from users:

"Unable to use arrows to navigate between cells if changing cell values"

## Tasks
- [ ] Discuss and document the requirement
- [ ] Identify feasibility of implementing as described
- [ ] Implement
- [ ] DOD

**Comment by utas-tajona** [comment]
very strange.... I can use the arrow to move from cell to cell. if it's editing a cell ESC allow me to move again

**Comment by ccmoloney** [comment]
Excel allows you to edit a cell  then navigate with arrow keys.  Our solution you need to hit Enter before navigating.

**Comment by utas-tajona** [comment]
Yes because arrows will move the cursor withint the cell.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3138)

**Comment by LizziOh** [comment]
This is working.  and very handy! thanks
