### ISSUE TITLE
Survey List:Survey Number - not relevant or correct;  no Survey Group ID

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#322]
Feedback from Lizzie - testing v0.0190:

>This seems to be the depth's decimal removed into another column.  It is not useful for ATRC, rather SurveyGroup is needed (way to group the 4 matching surveys (5.1,5.2,5.3,5.4)  together from the same site/date/depth integer (eg.5m) combo.  Also there are several non-0 records for RLS surveys, that do not appear to be part of a survey group (ie. related to ATRC sites on a trip where RLS volunteers replicated ATRC sites and did surveys in consecutive order)
We need to confirm the definition of survey group and number and implement properly.

Survey Number follows specifications according to https://github.com/aodn/NRMN/issues/63
implementation of a SurveyGroup identifier was not requested following https://github.com/aodn/NRMN/issues/224

**Comment by LizziOh** [comment]
To clarify further.  Depth needs to be stored correctly as a decimal depth, not the integer.  This is very important, despite displaying correctly in the endpoints.  
In addition to this change Survey Group implementation would be the desired additional feature to identify ATRC surveys

**Comment by LizziOh** [comment]
Could I confirm @bpasquer if the changes were purely front end - ie. changed views for survey list and edit survey in the UI or whether any fields in the database tables/schema was changed?

**Comment by bpasquer** [comment]
@LizziOh, changes were purely front end. 
Changing the depth to decimal necessitate a data model change, which would require more investigation.

**Comment by LizziOh** [comment]
Okay, thanks for confirming :)
