### ISSUE TITLE
Mapping of  measured Size class  to stored size classes incorrect 

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#339]
- M1 observable item  size measurements are ignored,  measurement of M1 observable item consistently set to  the Fish size class 
 measurement 'Unsized' 
- M2 observable item size measurements recorded with the 'UseInvertsizing' option set to 'YES' are recorded in Fish Size class AND M2 records are consistently set to measure_id =4  i.e. 7.5 cm whether the observation was sized or not and whatever the recorded size was.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3058)

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234

**Comment by LizziOh** [comment]
tested
