### ISSUE TITLE
Species validation checks don't take size mapping into account

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#345]
L5-L95 and Lmax validation checks currently check data against Fish size classes only. 
However, when the "With Extended sizes" option is selected,  size data map to Fish Size class of Inverts size class depending on the value stored in the "Use Invertsizing" column. 
As a result, L5-L95 and Lmax validation checks incorrectly report warnings for data measured in Invert Size. 

 The size class to use for the validation checks should be set by the value stored in the "Use Invertsizing" column: 
Yes: use InvertSize class
No: use Fish Size class

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234

**Comment by LizziOh** [comment]
Tested. Seems to be resolved.
