### ISSUE TITLE
Debris are entered as M2 but should be stored as M12

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#348]
Debris are counted/observed on Method 2 blocks in the field and entered as M2 in the datasheet.
However, Debris have their own method (M12) in the database.

Although entered as M2, Debris data should  be stored  on ingest in their own specific survey_method as M12

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3071)

**Comment by ccmoloney** [comment]
Should be resolved in version 0.0.234

**Comment by LizziOh** [comment]
I can confirm that in version 0.0.234 the staged data is accepting debris under method 2 and not accepting anything for method 12.  Not sure about the stored data once ingested.

**Comment by bpasquer** [comment]
I have verified that Debris are mapped to method 12 on ingest
