### ISSUE TITLE
Inconsistent formatting of survey checks feedback 

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#352]
The formatting of survey checks is inconsistent and could be improved for clarity and consistency:
For ex:
`BLOCKING: GSV13620/03/20195.11 invalid block combination`
`WARNING: [TAS406,1/12/2020,6] has incorrect set of methods: [1]`

A space between the elements of the site/date/depth combination would improve clarity and the block number should be clearly separated ( like in the above warning message).

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3105)

**Comment by LizziOh** [comment]
For the "survey exists" error what does the number following the brackets mean?  is it just the number of the first method entered for that survey?  I can't work out why its sometimes 1 and sometimes 2

**Comment by bpasquer** [comment]
The number displayed outside the bracket should be the decimal depth
