### ISSUE TITLE
PQ diver information should be stored in the table survey

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#357]
The information provided in the datasheet column 'pqs' ( PQ diver name) should be stored in the field `pq_diver_id` in the table survey.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3180)

**Comment by bpasquer** [comment]
PQ diver should be stored in a separate column from diver

**Comment by bpasquer** [comment]
The PQ diver column issue will be addressed in #607 
Closing

**Comment by bpasquer** [comment]
PQ diver information is now stored at survey level, but is currently not displayed in an endpoint.
Should we add a field "PQdiver" in the Survey_list endpoint?
