### ISSUE TITLE
Survey coordinates should be saved when they are not matching  the site coordinates

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#364]
Surveys can be done at a close distance from the site. When surveys Lat/Lon don't match site Lat/Lon then the coordinates need to be stored in the survey table  fields latitude and longitude.

## Tasks
- [ ] Save co-ordinates in the survey when they differ from the site coordinates
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3179)

**Comment by ccmoloney** [comment]
Will be resolved by https://github.com/aodn/backlog/issues/3126

**Comment by ccmoloney** [comment]
Should be resolved in the next release.
