### ISSUE TITLE
Blocking M3 transect quadrat sum under 50 feedback inappropriate

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#365]
The following feedback on M3 quadrat error is inappropriate. 

`BLOCKING: Transect: 10.1-BI-S1-17976 quadrats sum under 50.`
`BLOCKING: 10.1-BI-S1-17976: missing quadrats`

-  it is unclear what the number "17976" is referring to.
- the order of site code and depth (depth-site code) is inconsistent with other feedbacks (site-date-depth)

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3125)

**Comment by ccmoloney** [comment]
Should be resolved in the next release.
