### ISSUE TITLE
Value for Use InvertSizing column sometimes ERROR:#REF or ERROR:#N/A

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#370]
Some staged datasheets have values for the Use InvertSizing column for some rows which are 'ERROR:#REF' or 'ERROR:#N/A'.  Valid values for this column are 'Yes' or 'No'.

**Comment by ccmoloney** [comment]
![image](https://user-images.githubusercontent.com/30034813/120964913-6dc49e00-c7a7-11eb-8be8-97d291bf628c.png)

**Comment by ccmoloney** [comment]
![image](https://user-images.githubusercontent.com/30034813/120964943-79b06000-c7a7-11eb-8b6b-d8f2e29a18b0.png)

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3121)

**Comment by ccmoloney** [comment]
@LizziOh @atcooper1 Have you seen this for any sheets?  Is so: please attach them to this issue.  The sheet I saw it with will be attached below.  It has this issue in the source datasheet - so it doesn't seem to be a staging issue.

**Comment by ccmoloney** [comment]
[TestUI-Bicheno 2019_ready to upload.xlsx](https://github.com/aodn/nrmn-application/files/6699072/TestUI-Bicheno.2019_ready.to.upload.xlsx)

**Comment by atcooper1** [comment]
@ccmoloney there are usually a lot of #REF or #N/A errors in the "Invert sizing" column on incoming data sheets, but currently, these get processed the same as a  "No" record in the existing RLS ingest tool (so any records with a #N/A or #REF are saved using the fish size categories). I just tried a sheet with known #Ref values and I get the same result as you (ERROR:#REF)

![image](https://user-images.githubusercontent.com/50387396/123041484-b41d2c80-d438-11eb-8a63-5b1a505bdee6.png)

**Comment by ccmoloney** [comment]
@atcooper1 Thanks for checking :)  Maybe I'll load an issue about how we could interpret those as 'No' when the sheet is staging.  No promises it will be in the first release though ;)

**Comment by LizziOh** [comment]
Yes, these were actually from intentional errors I introduced to the datasheet to test.  N/A was from a row where I changed the method to 1 for a method 2 species, so it returned an NA (because the inverts sizing formula was looking in the wrong reference sheet for the species), and the REF was where I had a method 4, which has no lookup sheet.  Either way, when these errors occur they are from the uploaded sheets and can be adjusted in the staged data manually or before staging

**Comment by atcooper1** [comment]
@ccmoloney no probs at all!
