### ISSUE TITLE
WoRMS search  for valid species does not return results

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#376]
Eg. searched for Comanthus tasmaniae in WORMS, returned as unaccepted species and gives feedback that it is superseded by Cenolia tasmaniae.  But search for Cenolia tasmaniae returns no results.

**Comment by ccmoloney** [comment]
Using the webservice:

Searching by NAME (AphiaRecordsByName)
Records returned: 1
[] RECORD:Cenolia tasmaniae
  -  aphiaId         = 246735
  -  validAphiaId    = 246735
  -  authority       = (AH Clark, 1918)
  -  validAuthority  = (AH Clark, 1918)
  -  matchType       = like
  -  taxonomicRank   = Species
  -  taxonomicPhylum = Echinodermata
  -  taxonomicClass  = Crinoidea
  -  taxonomicOrder  = Comatulida
  -  taxonomicFamily = Comatulidae
  -  taxonomicGenus  = Cenolia
  -  STATUS          = accepted
  -  UNACCEPT_REASON = null

**Comment by ccmoloney** [comment]
Confirmed - our WORMS search in the UI doesn't return anything for "Cenolia tasmaniae"
Interestingly - searching for "tasmaniae" returns a list of results including Cenolia tasmaniae.

**Comment by ccmoloney** [comment]
But searching for Cenolia doesn't return any records...

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3128)

**Comment by ccmoloney** [comment]
Resolved in the next release.
