### ISSUE TITLE
Allow species name editing

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#379]
The Edit view should have all attributes displayed in the same format/order as in the View observable item view and have them all editable (except species ID). 

Note currently:  
- missing fields are superseded_names, superseded_ids
- read-only fields are Species Names, Species Epithet,Phylum, Class, Order, Family, Genus

**Comment by LizziOh** [comment]
Species Name is still not editable.  Is it possible to have this editable - eg. to correct misspellings? 
@atcooper1 do you agree?

**Comment by bpasquer** [comment]
We will allow the species name editing

**Comment by bpasquer** [comment]
trial as is for now and  see if it is practical
Rediscussed in future if not
