### ISSUE TITLE
valid entries for Superseded_by should come from dropdown menu only

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#381]
In the Edit Observable item view, Supersede_by values are provided in a drop down menu of valid species name to prevent circular reference and superseded species. 
However you can type in the box and save a species that is NOT selected from the drop-down.

Entries should only be allowed from the drop-down menu

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3130)

**Comment by LizziOh** [comment]
tested
