### ISSUE TITLE
Matching site code and site name check

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#384]
Need a validation check for incorrect match between site code and name in the data sheet

**Comment by ccmoloney** [comment]
Would this be a warning or a blocking check?

**Comment by bpasquer** [comment]
A warning according to Lizzie, TBC by Toni

**Comment by bpasquer** [comment]
Site code and site name don't always match according to Toni. For ex:  Sth entered instead of South in site name.
The check is not needed
Closing
