### ISSUE TITLE
New obs item - Aphia ID and relation not populated or saved from WORMS

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#386]
v0.0.234 
when adding a new observable item from WoRMS lookup, ' Aphia ID' and 'Aphia relation ' do not save

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3140)

**Comment by LizziOh** [comment]
tested
