### ISSUE TITLE
Default survey_num to 0 when depth entry is integer

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#390]
v 0.0.234:
a survey cannot be ingested when it contains integer depth entries as the system expect a decimal value to set "survey_num".
Generate the following error :
`ERROR: could not execute batch; SQL [insert into nrmn.survey (block_abundance_simulated, depth, direction, inside_marine_park, latitude, longitude, notes, pq_catalogued, pq_diver_id, program_id, project_title, protection_status, site_id, survey_date, survey_num, survey_time, visibility, survey_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [survey_num]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch`

Solution:
default survey_num to 0 when depth has no decimal value

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3142)
