### ISSUE TITLE
ATRC survey group complete check incorrect

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#421]
The ATRC survey group check verifies that ATRC surveys have 4 transects identified by the decimal part of the depth value and numbered from 1 to 4 See  [Validation check specs](https://universitytasmania-my.sharepoint.com/:w:/r/personal/cameron_moloney_utas_edu_au/_layouts/15/Doc.aspx?sourcedoc=%7B3C402E1B-6AC3-4C8B-A731-283FFF06B4F6%7D&file=NRMN%20-%20Specifications%20-%20Survey%20Data%20Validation%20Checks.docx&nav=eyJjIjo0Mzk4MzM3ODl9&action=default&mobileredirect=true&cid=b2b6cd3a-e740-4be2-809d-5c007c36bd46)  for reference 

Tested  with Maria_M3.xlsx returns : "ATRC Survey Group Complete: [MIR-S10,2/04/2019,5.1] is missing Method 2 Block 1"
Also note that : 
- the test seems to be checking if the ATRC survey is complete and is failing to identify all missing method and blocks
-  change the date format  for consistency with similar feedback messages i.e. 2019-04-02.

**Comment by LizziOh** [comment]
tested working
