### ISSUE TITLE
PQ column empty should be a WARNING not a BLOCKING validation check

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#430]
Software Version: 0.0.269

PQs can be empty or contain a '0'0 if PQs weren't done.

This should be a warning, not a blocking error.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3233)

**Comment by LizziOh** [comment]
this is now a warning which is good, but the validation seems to be that there has to be a 0 in the PQ column otherwise the warning occurs
