### ISSUE TITLE
Can't select and delete multiple rows in the staged data

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#433]
Being able to highlight and delete multiple rows from the staged data would be useful.

**Comment by LizziOh** [comment]
tested, but it still seems to only delete one row of data even when clicking the "delete selected rows" option that appears with multiple rows highlighted.

**Comment by bpasquer** [comment]
Closing as Lizzie could not reproduce the error.
Discussed an improvement lodged in https://github.com/aodn/nrmn-application/issues/575
