### ISSUE TITLE
HTTP 400 Error when editing a survey

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#483]
Software version: 0.0.318
Environment: Systest

From user:

> Error: Request failed with status code 400.  Happens when editing site code/name

## Tasks
- [ ] Resolve
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3316)

**Comment by LizziOh** [comment]
tested. resolved

**Comment by LizziOh** [comment]
tested and working
