### ISSUE TITLE
Filters not preserved for list pages

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#484]
Software version: 0.0.318
Environment: Systest

From user:

> filtering sites/surveys/obs items not preserved when opening and closing edit/view windows

## Tasks
- [ ] Implement preservation of filters for list pages
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3317)

**Comment by LizziOh** [comment]
tested and working
