### ISSUE TITLE
Method 0 Block 0 records should be allowed

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#485]
Software version: 0.0.318
Environment: systest

From user:

> Method 0 records showing warning error when block is 0
> Method 0 records are usually "off-transect" records so the block is usually entered as "0" as well - UI currently displaying error for block 0 (when Method is 0)

## Tasks
- [ ] Resolve
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3318)

**Comment by atcooper1** [comment]
It seems like this validation is expecting both block 1 and block 2 for any Method 0 records. Method 0 records should accept block = 0, 1, or 2.

**Comment by ccmoloney** [comment]
@nspool Can you please check what we are accepting for Method 0?

**Comment by nspool** [comment]
@ccmoloney method 0 is only accepting block 0.

**Comment by atcooper1** [comment]
![image](https://user-images.githubusercontent.com/50387396/128291605-7a3341e7-08d7-4228-b90e-68cbe247efe7.png)

**Comment by atcooper1** [comment]
I'm getting the error "Survey Incomplete: Method 0 is missing block 1, 2"

**Comment by nspool** [comment]
@atcooper1 this check hasn't yet been updated in SysTest. Just updated it this morning to only accept block 0, but will change it to accept 0, 1, or 2.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3331)

**Comment by LizziOh** [comment]
tested: method 0 now accepting block 0 in validations as well as block 1 and 2.
