### ISSUE TITLE
Group duplicate row feedback as a separate grouping in validation feedback

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#486]
Software version: 0.0.318
Environment: systest

From user:

> Would it be possible to list the duplicated row errors after the Blocking errors.
> These are the most important errors after the blocking errors and always need checking, currently they are getting lost in amongst the warning error list and it's difficult to navigate to them

> In addition, the user needs to be able to see the duplicated rows in relation to the whole survey. to be able to identify whether the duplication is a block entering error or whether the species has been entered twice throughout the sheet - currently can't distiguish this as the ID isn't carried through to the UI

##  Tasks
- [ ] Group duplicate row feedback as a separate section (displayed after the blocking errors)
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3319)

**Comment by LizziOh** [comment]
Now visible as separate group of validation warnings in staged data
