### ISSUE TITLE
Data summary in validation feedback not accurate

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#488]
Software version: 0.0.318
Environment: systest

From user:
> Not displaying correct feedback for a loaded sheet.
> i.e. loaded an ATRC sheet with 44 surveys from 11 sites all of which are complete, but the feedback says 5 surveys from 11 sites and 5 surveys incomplete

## Tasks
- [ ] Improve summary accuracy
- [ ] DOD

**Comment by atcooper1** [comment]
Number of rows in summary data still incorrect. (e.g. Canada Bamfield file has 1065 rows of valid data and UI is displaying 1085 in summary stats (was show 665 in previous version))
