### ISSUE TITLE
Survey Not Done not allowed for M3

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#489]
Software version: 0.0.318
Environment: systest

From user:
> Loaded an ATRC sheet where some surveys had in situ algae quadrats scored and some surveys had PQs taken.
> Added Survey not done for the M3 records where alge in situ quadrats were done, but the tool is expecting M3 records, need to accept "survey not done' for M3 as well as M1 and M2

## Tasks
- [ ] Modify validation to allow SND for M3 observations
- [ ] DOD

**Comment by ccmoloney** [comment]
@LizziOh @atcooper1 Is there a sheet that will show us the problem?  Or a screenshot?

**Comment by atcooper1** [comment]
Hi Cam, the Jurien sheet I ingested is a good example of Survey not done in M3? Are you able to view that in the UI? I can email you the sheet if you like?

**Comment by ccmoloney** [comment]
![image](https://user-images.githubusercontent.com/30034813/128285405-14ff9dbf-f78a-4788-a10d-4f9a622ff25b.png)

**Comment by ccmoloney** [comment]
When a Survey not done is recorded, the quadrat total checks shouldn't be applied.  Should the 'Total should be zero for SND' check be applied @atcooper1 ?

**Comment by atcooper1** [comment]
Yes. 'Survey not done' records are ingested but not displayed in the endpoints, so as long as SND ingest rules are consistent (either 1 or 0) across all methods/blocks it doesn't really matter. If current rules for Method 1/2 and Block 1/2 'Survey not done' entries are: Inverts/unsized and Total columns = '0' then stick with that for M3 "Survey not done" entries as well.

**Comment by LizziOh** [comment]
tested and working
