### ISSUE TITLE
New Site not being recognised in validation once created

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#490]
Software version: 0.0.318
Environment: systest

From user:
> Once a new site is entered - the UI doesn't recognise it and displays blocking validation error

Added site WA184 to create a new site associated with 'Dampier NEW SITE_DATA 2021_to_load_ATC.xslx
Subsequent validation still shows that WA184 is not a recognised site, despite the site showing in the site list etc.

##  Tasks
- [ ] Resolve
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3323)

**Comment by LizziOh** [comment]
tested, working
