### ISSUE TITLE
Debris Zero check incorrect

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#495]
Software version: 0.0.318
Environment: systest

From user:
> Debris zero is returning a blocking error if Total >0, but a warning error if total =0

> Debris zero needs to be entered either as a zero or as a non-zero in both the Total and Inverts/unsized columns, however the UI is returning erros for both options. It probably makes sense to accept Debbris Zero = 1 (so a '1' in the Invert/unzsized column which would return a '1' in the Total column)

## Tasks
- [ ] Resolve
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3325)

**Comment by ccmoloney** [comment]
@atcooper1 @LizziOh Can you just confirm what the valid values are for Debris Zero?  Either 0 in both Total & Inverts OR 1 in both Total & Inverts?

**Comment by atcooper1** [comment]
Hi Cam, A zero ('0') in the Inverts/Unsized column (and therefore also a '0' in the Total column) is ideal. Thanks!

**Comment by ccmoloney** [comment]
@atcooper1 the comment in the sheet said "or as a non-zero in both the Total and Inverts/unsized" what are the valid non-zero values?

**Comment by LizziOh** [comment]
There seems to be no warning related to Debris - Zero now.  Should the warning be if there is not a zero in the Inverts/Unsized column and Total column?

**Comment by atcooper1** [comment]
For RLS sheets, Debris Zero records throwing blocking error: "Debris has Value/Total/Inverts no 1 or 0". Have tried adding zeros or 1's to both total and inverts/unsized columns but error won't resolve?

**Comment by atcooper1** [comment]
For ATRC sheets, Debris Zero checks not being performed at all. (e.g. dummy data sheet in Jobs has Debris Zero in row 33 where totals are not 0 and Total column  and Inverts/unsized column are not equal but not getting any errors)

**Comment by bpasquer** [comment]
> For ATRC sheets, Debris Zero checks not being performed at all. (e.g. dummy data sheet in Jobs has Debris Zero in row 33 where totals are not 0 and Total column and Inverts/unsized column are not equal but not getting any errors)

The check was no applied because the api uses the code 'dez' to identify 'Debris -Zeros' and the code was missing at that row

**Comment by bpasquer** [comment]
>For RLS sheets, Debris Zero records throwing blocking error: "Debris has Value/Total/Inverts no 1 or 0". Have tried adding zeros or 1's to both total and inverts/unsized columns but error won't resolve?

I haven't been able to replicate it. What sheet were you testing @atcooper1 ?

**Comment by atcooper1** [comment]
No checks should rely on the "Code" column. The code is meaningless for data quality (it is purely available as a shortcut to make entry faster). Can the check be on the "Species" name column instead? Does the API also do this for species (i.e. no checks for species where Code = blank)? As this will also be a problem?

**Comment by bpasquer** [comment]
>  Can the check be on the "Species" name column instead?

Yes we will make this change

>Does the API also do this for species 
No, it was specific to 'Debris Zero' and 'Survey Not done' checks

**Comment by bpasquer** [comment]
Fix will be applied to ATRC to

**Comment by bpasquer** [comment]
Update :
The 'Debris Zero' check is now applied to both RLS and ATRC

**Comment by LizziOh** [comment]
tested
