### ISSUE TITLE
Edit Survey: site code/name behaviour inconsistent

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#496]
Software version: 0.0.318
Environment: systest

From user:
> Edit surveys: if site code is changed the the site name changes to match.... but not vice versa

> its also unclear whther there are validations that would prevent saving an incorrect site name to site code match... because error 400 occurs for any site change.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3326)

**Comment by LizziOh** [comment]
tested and working
