### ISSUE TITLE
Survey List: sorting not adequate

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#497]
Software version: 0.0.318
Environment: systest

From user:
> Survey List: Initial sorting is unclear and can only sort by site name

> cannot sort by most fields including SurveyID.

##  Tasks
- [ ] Identify required default sort order & which fields should allow sorting
- [ ] Implement
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3327)

**Comment by LizziOh** [comment]
tested and working
