### ISSUE TITLE
Diver name and initial validations should be case-insensitive

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#498]
Software version: 0.0.318
Environment: systest

From user:
> Validations for add new divers and diver initials don't appear to be case sensitive.

> added divers to test:  LIZ oh (eso), Liz OH (asdf) alongside the existing Liz Oh (ESO).  also the first one doesn't appear to sort next to the others because of case?

## Tasks
- [ ] Make validation checks case-insensitive
- [ ] DOD

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3328)

**Comment by LizziOh** [comment]
Note though that this is **different** to the validations for staging and ingesting survey data.  The checks on the diver column should not be case sensitive for ingest validations.  For example if data is ingested with "liz oh" in the diver column, we want it to match to the saved diver "Liz Oh".  This request only applies to the reference data management "Divers" ie. we only want one "Liz Oh" to be able to be saved in the DB, regardless of case.

**Comment by LizziOh** [comment]
teseted and working
