### ISSUE TITLE
Valid M2 familiy names displaying as invalid species

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#499]
Software version: 0.0.318
Environment: systest

From user:
> Valid M2 families are returning warning errors as "invalid). e.g. Apogonidae spp.

## Tasks
- [ ] Resolve
- [ ] DOD

**Comment by ccmoloney** [comment]
@bpasquer Can this be resolved using the method/species mapping table in the DB?

**Comment by ccmoloney** [comment]
Apogonidae spp. is currently not mapped to Method 2 - it is mapped to methods 0 & 1
@atcooper1 @LizziOh Is this incorrect?

The software seems to be working properly - but we haven't specified that family as being a valid method 2 species.

**Comment by bpasquer** [comment]
> @bpasquer Can this be resolved using the method/species mapping table in the DB?

Yes

**Comment by bpasquer** [comment]
Actually, Apogonidae is correctly mapped to method 2:

```sql
select method_id, observable_item_ref.observable_item_id,observable_item_ref.observable_item_name,family from nrmn.methods_species 
join nrmn.observable_item_ref ON observable_item_ref.observable_item_id = methods_species.observable_item_id 
where family='Apogonidae' and method_id=2
limit 10
```

| method_id | observable_item_id | observable_item_name      | family     |
|-----------|--------------------|---------------------------|------------|
| 2         | 812                | Apogon ruepellii          | Apogonidae |
| 2         | 5342               | Nectamia ?luxuria         | Apogonidae |
| 2         | 6152               | Taeniamia laei            | Apogonidae |
| 2         | 1201               | Vincentia badia           | Apogonidae |
| 2         | 39                 | Vincentia conspersa       | Apogonidae |
| 2         | 2112               | Vincentia novaehollandiae | Apogonidae |
| 2         | 2125               | Vincentia punctata        | Apogonidae |
| 2         | 6121               | Zoramia spp.              | Apogonidae |
| 2         | 5626               | Zoramia fragilis          | Apogonidae |
| 2         | 4902               | Zoramia leptacantha       | Apogonidae |

**Comment by ccmoloney** [comment]
But not Apogonidae spp.

**Comment by bpasquer** [comment]
There is no 'Apogonidae spp'  family, 'Apogonidae spp' is an observable item name 😉

**Comment by LizziOh** [comment]
I think this is what Toni is referring to.  We need the Apogonidae spp. observable item name (id 1323) to be listed as an M2 observable item.  It is used when we make an observation from that family that we can't identify to species level.

On further look, there maybe a problem with a circular superceeding reference between Apogonidae spp. and Apogonid sp. in the database (or at least in test).
![image](https://user-images.githubusercontent.com/52521522/128660463-93578dc9-2ecd-4105-9806-97d8e3828f7e.png)

**Comment by LizziOh** [comment]
this is related to a backlog issue 
https://github.com/aodn/backlog/issues/3346 

Incorrect method species warnings occur newly added species.

**Comment by bpasquer** [comment]
> Incorrect method species warnings occur for newly added species.

this is similar to https://github.com/aodn/nrmn-application/issues/550
and we have a backlog  to address it https://github.com/aodn/backlog/issues/3348
At this stage,  the process to assign newly added species to methods and set "is invert sized" runs overnight
There are 2 solutions :
- improve the "add Observable Item" view to allow a user to specify the method and Invert/Fish size
- run the process that automatically set these attributes on ingest

**Comment by LizziOh** [comment]
If this runs over night and assigns the "Is invert sized" information then I would be happy with that. This doesn't seem to be the case at least in systest though?  I'm still getting "method xx is invalid for species" warning for methods 1,2, and 3 for species I entered into systest days ago.  eg. Sargassum oligocystum (M3), Halimeda spp. (M3), Siphamia cuneiceps (M1), Timbellus bednalli (M2).  Is this more related to the observable item type and hence we need to set that when creating a new item?

**Comment by bpasquer** [comment]
This is a very recent improvement. It might not have been deployed to systest as we had technical issues deploying changes this week.
