### ISSUE TITLE
Need to see how far coordinates are from Site coordinates

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#503]
Software version: 0.0.318
Environment: systest

From user:
> Need to see how far the entered coordinates are from the Site coordinates, this check is in the current tool and helps us determine whether a site was entered at different coodinates in error or intentionally - not just for a distance of more than 200m)

##  Tasks
- [ ] Determine (in consultation with users) the best way to display this information
- [ ] Implement
- [ ] DOD

## PRs
- https://github.com/aodn/nrmn-application/pull/505

**Comment by ccmoloney** [comment]
@atcooper1 Can you put a screenshot in this issue showing how this information is currently displayed?

**Comment by ccmoloney** [comment]
![image](https://user-images.githubusercontent.com/30034813/128285071-d297cb5b-d829-4ec5-bfab-4a6e9187d838.png)

**Comment by bpasquer** [comment]
A warning is raised when the survey coordinate is different from the site location and the distance from the site location is displayed in the warning message on the left hand side as well as  by hovering over the affected cell: 
![Screenshot from 2021-11-25 10-06-49](https://user-images.githubusercontent.com/3733612/143323793-b076a759-5f55-4864-9a9d-eea6687b6e9a.png)

**Comment by bpasquer** [comment]
Can we close?

**Comment by atcooper1** [comment]
I'm not sure this is working for coordinates within 200m of an existing site? I've just tested by changing coordinates (so the distance is <200m from site coords and i'm not getting any warnings? Historically we would get a warning message to say ## sites existing, ## site mismatched coords - then a list of the sites with mismatching coords and the distance from the site (i.e. 33m)

**Comment by bpasquer** [comment]
Sorry yes you are right, it is not providing the distance information if the location is withing 200m.
