### ISSUE TITLE
Tool now seems to be cutting excess rows, but also last row of valid data

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#519]
Software version: 0.0.337
Environment: systest

From user:
> Tool now seems to be cutting excess rows, but also last row of valid data

## TASKS
- [ ] Identify
- [ ] Fix
- [ ] DOD

**Comment by ccmoloney** [comment]
@atcooper1 Do you have a sheet that demonstrates this?

**Comment by atcooper1** [comment]
The sheet "PS7_KHVT7m31072021LittleBeachFAKECOORDTEST.xlsx" (currently in my jobs list) demonstrates this error.

**Comment by nspool** [comment]
@atcooper1 Which row is missing in the staged sheet? Both appear to be showing 466 rows.

**Comment by atcooper1** [comment]
The problem is that it that the tool is recognizing the excess rows as duplicates (displayed as warnings), but not recognizing the last row of valid data (still the case in 0.0.342).  
![image](https://user-images.githubusercontent.com/50387396/129282319-2df75a34-a991-41e7-b189-2236ff7e1a90.png)

**Comment by ccmoloney** [comment]
@atcooper1 What is the last valid row of data?  And how do we detect it?

**Comment by atcooper1** [comment]
I thought you were going to use the "detect 3 duplicate rows" rule? But as I mentioned last week, there also needs to be an additional rule depending on the last observable item. There are two different scenarios: where data finishes with a true zero, or a species. I’ve highlighted the **last row**s of valid data in 2 examples.

For sheets that end with Survey not done, Debris Zeros and No species found: if the UI finds 3 rows of duplications (total = 0), the first row (highlighted) is in fact a valid row of data so the UI should cut the SECOND duplicated record:
![image](https://user-images.githubusercontent.com/50387396/129284063-ba66062e-db80-4cbd-b634-7c3ab053b603.png)


Whereas if a sheet finishes on a species, then the FIRST duplicated row (where total =0) should be cut (i.e. the row below the highlight):
![image](https://user-images.githubusercontent.com/50387396/129284071-896c58f0-9b14-43dd-a356-9f1e3bdb552e.png)

 Hope that makes sense?

**Comment by LizziOh** [comment]
this is related to issue #506 
https://github.com/aodn/nrmn-application/issues/506#
