### ISSUE TITLE
Find/replace not working for some search terms

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#532]
Software version: 0.0.344
Environment: systest

From user:
> find and replace not working.  Find all works but replace all doesn't

> For example, tried to replace Bare rock (non - barrens) with Bare rock

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3345)

**Comment by LizziOh** [comment]
tested/working
