### ISSUE TITLE
M3 data can be split across multiple rows in the staged data & should be summed on ingest

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#535]
Software version: 0.0.344
Environment: systest

Raised during testing:
> warning when duplicate rows are not adjacent to each other.  That's okay, but these are summed on ingest right?  Very common in M3 for species such as Unidentified foliose red algae

This implies that M3 data may come in in a datasheet with multiple rows, each one containing the data for one quadrat.  These rows should not be interpreted as duplicate rows - as long as they don't contain data for the same quadrat as another row.

The ingest code should combine the quadrats.

The validation rules should identify missing quadrat data by looking at all of the related rows and identifying if there are any quadrats missing.

**Comment by LizziOh** [comment]
Discussed in meeting and Bene confirmed that the duplicates are not summed on ingest, but are summed in the endpoints.  Similar to previous databases.  Warning validations persist for these examples, which is okay.  However it would be good if these did not replicate for each matching duplicate row, rather there was a single warning which pointed to multiple rows.  As mentioned it would be good to delineate which row an error points to more clearly - either by highlighting it a different colour, or with a coloured rime around the highlighted error cells.  This helps when the rows are spread out beyond the visible window and you can scroll and identify to the rows.
