### ISSUE TITLE
Old site codes shouldn't be cloned when cloning a Site

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#540]
Software version: 0.0.344
Environment: systest

From user:
> When cloning a site to make a new site, it duplicates metadata that you have no option to edit. 

> Eg. the old site codes of the one you duplicated are copied to the clone without you seeing this. this is incorrect and only apparent on saving and then reopning the site.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3349)

**Comment by LizziOh** [comment]
tested/working
