### ISSUE TITLE
AS A user I WANT to enter old site codes when I create a new site SO THAT i don't have to create it and then edit it to add the old site codes

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#542]
From user:
> At the time of creating the new site from the clone: you have to save it, find the site, view it to make sure there was no superfluous cloned information, delete the old site codes & then enter the new ones.  The form for creating a new site doesn't include "old site code".

It would be useful if the user could enter old site codes at the time they create a new site.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3350)

**Comment by LizziOh** [comment]
test/ working.
Old sites codes now editable after cloning a site. A small bug remains:  after you remove the old site code it keep reappearing when you edit any other field.

**Comment by bpasquer** [comment]
> A small bug remains: after you remove the old site code it keep reappearing when you edit any other field.

@LizziOh , the bug will be addressed in https://github.com/aodn/nrmn-application/issues/563
