### ISSUE TITLE
NRMN pipeline : Endpoint extraction fails on 10-aws

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#557]
This is the error according to the notification email:

`From: Cron Daemon <root@10-aws-syd.emii.org.au> Date: Friday, 13 August 2021 at 9:00 pm To: Benedicte Pasquer <benedicte.pasquer@utas.edu.au> Subject: Cron <projectofficer@10-aws-syd> /mnt/ebs/data-services/NRMN/extract.sh
Unable to run extract as /mnt/ebs/incoming/NRMN is not empty`

I thought that the file pushed to the incoming was moved /deleted from the incoming during the processing.
But apparently, it was not in this instance.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3382)

**Comment by ccmoloney** [comment]
@bpasquer Did this one get resolved?

**Comment by bpasquer** [comment]
Resolved
