### ISSUE TITLE
Ingest Summary improvements

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#561]
Software version: 0.0.361
Environment: systest

From user feedback.
- the list of distinct sites,observable_items, and divers in the summary check should include new ones
- could provide the list of found sites
- could provide the site/date/depth/method combo of incomplete surveys in a drop-down

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3384)

**Comment by bpasquer** [comment]
Further from the improvements covered in https://github.com/aodn/backlog/issues/3384

From Toni's email:
Rows:
- ~number of distinct rows of data found~

Sites:
- ~number of  distinct sites found~
- number of  existing sites
 - number of sites with mismatching co-ordinates + list  of which SITE_CODE, DATE, DEPTH is mismatching and how many metres it is away from the true Site
-~number of new  sites found +  list of which sites are new~

Surveys:
- ~number of distinct surveys found~
- number of existing surveys
- ~number of new surveys~
- ~number of incomplete  surveys~ + list of complete surveys and highlighted incomplete surveys in a SITE_CODE, DATE, DEPTH format

Observable items: 
- ~number of distinct observable items found~
- number of known observable items
- ~number of new observable items~ + list of new observable items

Divers:
- ~number of  distinct divers found~
- number of existing
- ~number of new~  + list which divers are ‘new’ 
 
 Note that lists of new items(Site, observable items, divers) are already provided under the blocking checks.

**Comment by bpasquer** [comment]
> Divers:
> 
> * ~number of  distinct divers found~
> * number of existing diver
> * ~number of new~  + list which divers are ‘new’

The diver summary currently covers the field "Diver" only.

It should also summarise the data in the Buddy and PQ diver columns

**Comment by atcooper1** [comment]
Summary working, however missing " ## Existing surveys found" after "## surveys incomplete". It would be helpful to know how many surveys are existing so you know if the whole sheet is a duplicate or there are still new surveys attached to the file as per: 
![image](https://user-images.githubusercontent.com/50387396/131422692-740b698c-4a40-46c5-b84a-71fff2ae378a.png)

**Comment by LizziOh** [comment]
Ingest summary provides #Existing surveys and #incomplete surveys.  However in the example below it returned "-7" new divers?
![image](https://user-images.githubusercontent.com/52521522/134109882-5a1497ae-04cd-4abe-b0a6-7ff0688ba0f7.png)
NOTE: When the blanks in buddy columns were fixed this changed from 8 distinct and -7 new, to 7 distinct and -8 new . So perhaps the changes to buddy column are affecting this?

**Comment by LizziOh** [comment]
Update: Systest has been updated again and the divers count issue mentioned above has been resolved.

**Comment by atcooper1** [comment]
The diver summary is not working correctly. I think perhaps the tool is summing both Initials and Names for the same diver as listing them as unique records, resulting in twice the number of divers.

**Comment by nspool** [comment]
@atcooper1 That's right. If a diver was entered with their name in one column and initials in another, it was recording two different divers. This should now be fixed in SysTest.
