### ISSUE TITLE
Data extract for publication to Geoserver should run nightly

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#564]
The current schedule for the cron job that extracts data to be published to the AODN portal is to run weekly.  The schedule should be adjusted to run the extract every night.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3391)

**Comment by bpasquer** [comment]
I confirm that the cron run nightly
