### ISSUE TITLE
Direction 'S' invalid

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#582]
Environment : systest
version : 0.0.375

Datasheet: Ningaloo DATA_combined.xlsx
The validation of ~350 out of ~1200  rows with Direction 'S' are blocking the ingest of the datasheet. 
Re-entering   'S' in the impacted cells does not solve the problem.

**Comment by ccmoloney** [comment]
Kamino cloned this issue to [aodn/backlog](https://github.com/aodn/backlog/issues/3405)

**Comment by atcooper1** [comment]
All directions working
