### ISSUE TITLE
Duplicate row validation highlights rows with different species and incorrectly checks total column

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#583]
environment :systest
version: 0.0.375

ex: Ningaloo DATA_combined.xlsx

When multiple duplicate rows are found on the same site/date/depth/block,  rows with different species( i.e. not duplicated rows) are grouped and highlighted as dupicates.

Duplicate row warning messages should  group and highlight duplicates by species

**Comment by atcooper1** [comment]
As discussed on Friday 27/08 It was agreed that an additional highlight is needed when the UI identifies duplicates and the user clicks a duplicate to view it in the sheet. Currently it is difficult to see which cell the UI is referring to when multiple "duplicates" are highlighted. Need to know which error message is referring to which cell. In addition, filters need to be maintained when a user clicks an error so the error can be visualized within the extent of the survey in question

**Comment by bpasquer** [comment]
As discussed at the meeting Thursday 02/09 
'Total' should be excluded from the rule to identify duplicates
