### ISSUE TITLE
Standard headers checks failing to raise missing header error on invert size header row 

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#585]
Structural checks verify based on headers that a datasheet contains the required columns. Headers are present in the first 2 rows of a valid datasheet.  This is reflected in the validations checks "Standard Headers OK " and "Extended Sizing Headers OK" .

As a result, it implies that observations are recorded from row 3.

The file Dummydata-JMP-S45_B.xlsx was purpose-made to test the software and its structure was simplified by removing the second row of headers (the invert size header row ). But although it lacks the second row of headers, it was validated.
[Dummydata-JMP-S45_B.xlsx](https://github.com/aodn/nrmn-application/files/7042850/Dummydata-JMP-S45_B.xlsx)

As a result, the first row of data is not being staged.

The Standard Headers check should be correctly applied to verify the presence of the second row of headers and ensure that all the observations are staged.

**Comment by atcooper1** [comment]
This is related to issue #594 
The existing RLS tool checks for 'compliant column headers', checks that the "Data" worksheet has a blank formatted row 2, and that the "Data" worksheet has data starting from row 3. If these aren't compliant, then the user can't continue (stage) the datasheet and will need to amend the sheet. These same rules should be applied to the UI.

**Comment by LizziOh** [comment]
I can confirm that the UI now blocks staging if the second header row is missing.  183 rows of data were staged for both RLS and ATRC program selections for the test file "Dummydata-JMP-S45_B.xlsx" when a second blank row was added
