### ISSUE TITLE
Which visibility value should be stored when different value are recorded during a survey?

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#589]
In the datasheet,  the visibility is recorded at block level.
In the NRMN DB the visibility is stored at survey level.

This can lead to discrepancies in the recorded value when during a survey the visibility differs from one block to the other.

Is storing only one value an issue? If yes, then what should we store?

**Comment by atcooper1** [comment]
The average for that particular survey (date/depth/site combo) @LizziOh

**Comment by LizziOh** [comment]
Yes, the average would be good.  Would integers be best though?  eg. average the multiple entries, then round down to the nearest integer?  that way is doesn't give the illusion that we are extremely accurate in our estimates...  @atcooper1

**Comment by atcooper1** [comment]
Agreed. Average vis and round to the nearest int.
