### ISSUE TITLE
Survey exists validation not consistent

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#590]
environment : systest
version: 0.0.381

From user:
>For a staged sheet with 4 existing surveys pressing validate returns different numbers of "survey exists" errors at different times.  For example in this pic, only 3 out of 4 are found and the description of the 3rd one is identical to the first one but points to a line with 2.3m (survey group 3) not one as the description suggest? These glitches seem to resolve when saving and validating multiple times, but odd.  Regardless the description could be improved by including other the decimal depth / survey group in there.

**Comment by LizziOh** [comment]
I agree with the improvement to the feedback - that the number after the brackets should reflect the decimal depth.

Regarding the inconsistencies, it is like a few different errors that we have come across... some times the validations glitch.  So it may not be a problem with the validation itself, just general "glitches" that sometimes produce errors, or omit errors - usually resolving themselves with further "save and validate" actions.
