### ISSUE TITLE
UI doesn't identify when there is data in row 2 instead of blanks in the first columns (A:J) of templates

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#594]
UI doesn't identify when there is data in row 2 instead of blanks in the first columns (A:J) of templates. This occurs when someone has deleted the 2nd header row, or if the data is downloaded from the NRMN staging/validation tool (eg. to make a special edit after fixing some things in the tool).  If re-staged without the 2nd header row the NRMN UI currently does not stage the 1st row of data.  RLS database wizard currently identifies this (as shown in the attached document's pictures and discussed with Tanjona - but we missed this in the validation requirements documents).

[Current_validation_checks_20200430.docx](https://github.com/aodn/nrmn-application/files/7081193/Current_validation_checks_20200430.docx)

Note: it would be better if the UI did include the 2nd row of headers when downloading the data from the staging view of the UI

**Comment by bpasquer** [comment]
will be addressed in #585
closing
