### ISSUE TITLE
Need an "Undo" button or a working "history" that allows the user to override a 'save'

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#595]
Unable to re-trace steps if an error is made inside the UI. Once user hits "save and validate" the sheet/UI jumps back to the top and removes current filters making it impossible to find where the new introduced error is.

**Comment by LizziOh** [comment]
Filters are now retained when "save and validate" is pressed.  
ctrl-z still does not work for actions made before saving, but the issue has improved with the above change.  
@atcooper1 you can close this issue if happy with the fix

**Comment by atcooper1** [comment]
Yes, this is an improvement, although now I consistently need to hit "save and validate" twice before the error clears. 
I still think an action history is really important here as there is no way of backtracking once you move to another warning error.

**Comment by bpasquer** [comment]
Nathan to scope out a tracking history solution.
