### ISSUE TITLE
Creating a new site- accepts any entry for Country and State

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#596]
Currently the API that would auto-assign a country and state to a new site based on its coordinates cannot be reliably implemented .  For now the details are manually entered, however we need a solution to stop different spellings of the same country or state creeping in. 
Is it wise in the interim (before a sophisticated solution is found), for there to be a drop down menu that suggests countries already existing in the DB?  Is it also possible to have a drop down menu for state, which filters based on the country that is entered?  Of course we still need the possibility of adding new countries and locations, so free text should still be allowed.

**Comment by bpasquer** [comment]
a drop down of values available in the database could be sufficient
