### ISSUE TITLE
Creating templates using Location

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#597]
Currently, the filters only work if a user begins to prefill the filter with text, so this relies on the user to know exactly what results are in each field, (i.e. there is no option of viewing all unique records within a column). This causes problems when trying to create a template using multiple Locations (i.e. to create a Northern Western Australia template the user needs to know that the Locations are Ningaloo Reef, Ningaloo Reef - North, Exmouth, Ashmore/Cartier, Scott & Seringapatam Reefs, Kimberley, Abrolhos (WA), Pilbara, Rowley Shoals) because there is no way of easily looking at the unique Location values under the Sites view (other than manually scrolling, which introduces errors). Similarly, the Location view only shows Location - there is no reference to the State/Area it belongs to. 
For a user to create a template using a subset set of Locations within a State/Area and Country, the current workflow will require the user to download the latest site list off the Geoserver, subset it to see all the unique values for Location within a State/Area and then go back to the UI and manually type in the appropriate records in the search and add them individually. 

If the user could filter hierarchically when creating a template (i.e. filter on Area/State, then Location and be able to see (and select) all unique values within that search that would be very helpful. 

In addition, if the higher geographic groupings (i.e. Eco region, Country, Area) could be added to the Locations view that would also help.

"Country" is also missing from the template generator.

**Comment by bpasquer** [comment]
As discussed, the location List view could have seperate filterable columns for Eco region, Country(comma separated), and Area(comma separated)

**Comment by LizziOh** [comment]
Location list changes have been implemented correctly

**Comment by bpasquer** [comment]
Closing. A new issue will be open to scope out the hierarchical listing of fields in the template generator
