### ISSUE TITLE
Location View needs Hierarchical geographic info 

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#598]
State/Area, Country, Ecoregion etc need to be added to the Location view. These need to be filterable.  
On rare occasions, Locations span across multiple states or countries so this would need to accommodate multiple values in these fields. In the absence of an API to geo-reference States within Country etc, this could be generated from the Sites list?

This is related to issue #597 and #596

**Comment by bpasquer** [comment]
will be addressed in #597 
closing
