### ISSUE TITLE
"Inverts is not an integer" blocking error

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#601]
Inverts/unsized column should either: display _all_ rows affected (as User currently needs to manually add zeros to Inverts/unisized column survey-by-survey which is very tedious for large files) or allow zeros _and_ blanks.

**Comment by atcooper1** [comment]
This is the same with "BUDDY" column. User needs to change BUDDY to "0" survey-by-survey. Suggest either UI allows "Buddy" and converts to "0" on ingest, or displays all "BUDDY" values so User can change all at once.

**Comment by LizziOh** [comment]
UI validation error now filters blank cells from all affected surveys in the staged sheet at once - so fixes can now be made in one go. This works for both the inverts and buddy column  
@ atcooper you can close this if you're content with the change
