### ISSUE TITLE
Edit Survey improvements 

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#608]
Should accept blank direction
Should accept dates from 1991 for ATRC

**Comment by LizziOh** [comment]
Should also accept a blank for PQ diver, instead of "unknown diver" as this is incorrect really.  Often there are no PQs taken for ATRC surveys so should be blank and not assumed to be "Unknown Diver".

When editing a site and a new site code is selected, the matching site name auto fills.  Can we also auto fill the matching site latitude, longitude, protection status and "is in Marine Park" data?

**Comment by bpasquer** [comment]
> Should also accept a blank for PQ diver, instead of "unknown diver" as this is incorrect really. Often there are no PQs taken for ATRC surveys so should be blank and not assumed to be "Unknown Diver".
> 
> When editing a survey and a new site code is selected, the matching site name auto fills. Can we also auto fill the matching site latitude, longitude, protection status and "is in Marine Park" data?

these improvements will be addressed  as a separate issue in #623

**Comment by LizziOh** [comment]
Not yet fixed in version 1.2 (386)

**Comment by LizziOh** [comment]
Still not fixed in systest release Version 2.0 (403) ?

![image](https://user-images.githubusercontent.com/52521522/134098625-6c8b6115-e6fc-417e-ae29-9a7451a6088b.png)

**Comment by LizziOh** [comment]
Update: Nathan's put a new fix in for the blank direction and the ATRC start date in systest.

Tested and it's working
