### ISSUE TITLE
'Has PQ catalogued in DB'  field values 

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#610]
On 06/09 @LizziOh noticed that has_pq_catalogued_in_db values stored in the endpoint ep_survey_list  and those displayed in the UI in the DB are different, in particular, ATRC survey for which the field should be 'False' is all set to True in the endpoint.

Bote that Squiddle relies on this field.

Task :
- [x] Investigate
- [x] Resolve

**Comment by bpasquer** [comment]
the materialized view has been updated  both in systest and prod. 
@LizziOh can you please confirm  values of "has_pq_catalogued_in_db' are  correct now

**Comment by LizziOh** [comment]
yes things look good now.  The ATRC surveys are nearly all FALSE as expected.
I cross checked against the old survey list from the geoserver and there are only 21 RLS surveys that mis-match between the lists - these are set to TRUE in NRMN and "no" in RLSdb SurveyList... However the ones I checked are on TPAC and the PQZipURLS work so the NRMN endpoint seems to be the correct one. 
[test_survey_list_haspqs_prod.xlsx](https://github.com/aodn/nrmn-application/files/7125311/test_survey_list_haspqs_prod.xlsx)

I'm content this is issue is resolved
