### ISSUE TITLE
Survey edit - improvements

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#623]
- [ ] edit Survey should  accept a blank for PQ diver
- [ ]  the survey details view should also accept blank for PQ diver instead of "unknown diver" as this is incorrect really.  Often there are no PQs taken for ATRC surveys so should be blank and not assumed to be "Unknown Diver".

- [ ] When editing a survey and a new site code is selected, the matching site name  , site latitude, longitude protections status and 'Is in Marine Park'  auto fills.  

_Originally posted by @LizziOh in https://github.com/aodn/nrmn-application/issues/608#issuecomment-913307631_

**Comment by nspool** [comment]
This appears to have been resolved.  Closing.
