### ISSUE TITLE
Group Warning errors into "Warning errors" and "addition info" warnings

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#652]
Perhaps move Exceeds max size and Exceeds max abundance warnings down to an "additional Info" warning section to allow user to prioritize important warning errors.

**Comment by bpasquer** [comment]
Errors and warnings are now presented in 4 sections: "Blocking", "Duplicate","Warning" and "Info".
The Info section lists warnings for "Measurement is above Lmax", "Measurement outside L5/95" and "Exceeds max abundance".

Can we close?
