### ISSUE TITLE
Create a filter for all "Record has no data but not flagged as survey not done or species not found" warning errors

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#654]
If all "Record has no data but not flagged as survey not done or species not found" warning errors could be grouped, and affected observations be filtered to allow the User to copy and paste values from "Total" column to "Inverts" column, this would save a huge amount of time.

**Comment by bpasquer** [comment]
Warnings for "Record has no data but not flagged as survey not done or species not found" are grouped and presented into subgroups organised by "Total", as shown in the example below:

![Screenshot from 2021-11-25 09-30-07](https://user-images.githubusercontent.com/3733612/143320931-088207cb-3219-400a-a479-b9fe0264d4f2.png)
Does the current grouping and sub-grouping useful and suiting your requirement or  is it one grouping level too much?
