### ISSUE TITLE
Species Epithet is mandatory field to populate when adding a new Observable Item, but it shouldn't be

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#675]
Many existing observable items have no Species Epithet, so it is inconsistent that every new obs item should have one.  Species Name should be mandatory.  But not all obs items need a species epithet because sometimes we make observations at a higher taxonomic or functional group level if species cannot be identified

**Comment by LizziOh** [comment]
species epithet is still prefilled with a duplicate of the genus name if a genus only observable item is created from the worms look up.  Eg.  if wanting to create Plagusia spp. as the species name, you find the genus Plagusia in worms but it still replicates "Plagusia" in the epithet and genus fields, instead of just the genus field and leaving epithet blank

**Comment by bpasquer** [comment]
VERIFIED
