### ISSUE TITLE
Rule for blank row 2 not acting as it should

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#678]
When User has to manually insert a blank row 2 (e.g. where the diver has deleted it during consolidation), the validation rule should not fail because "Row 2 missing headers  1, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 100, 120, 140, 160" It should be possible to load the sheet with these fields blank.

**Comment by nspool** [comment]
Only check for blank column A-G.

**Comment by LizziOh** [comment]
tested in systest, staged file with  blank 2nd row successfully
