### ISSUE TITLE
Blocking error "Debris has Value/Total/Inverts not 0 or 1" only returning 1 row of this error

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#684]
This blocking error seems to only return 1 or 2 errors per survey so the User has to fix the Debris error for 1 survey, 'save', then the next Debris error will become visible. It would be great to be able to see all of these errors for the whole sheet in one go (filtered) so the User can fix them all at once, as it takes a very long time to do this survey by survey.

**Comment by nspool** [comment]
Use filtering for non-duplicate row validations.

**Comment by LizziOh** [comment]
tested in systest, works well :)
