### ISSUE TITLE
Additional ATRC survey data not migrated? (see issue #115 in NRMN repo)

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#689]
https://github.com/aodn/NRMN/issues/115

As per issue above, which has not been resolved.  The issue states that  the step "include additional m2 data transects into survey_method.sql re-coded for being Block 2 on the corresponding survey" has been completed, but it does not appear that way.

These additional data should be included in M2 related endpoints as M2, block2

**Comment by bpasquer** [comment]
Although the second comment of https://github.com/aodn/NRMN/issues/115 states that the additional m2 data transects have been included in the migration code, the following comment:
https://github.com/aodn/NRMN/issues/115#issuecomment-547192301

states that they have been intentionally "un-included" 

and in  https://github.com/aodn/NRMN/issues/115#issue-508229974 :
>"the additional data surveys identified in this issue have been excluded from the data migration: i.e. survey and survey_method records won't be created during migrate. As a result, no observations will be migrated either. With the analysis and data recorded in this issue, the additional data M2 surveys can be ingested post migrate."

We have 2 options to bring these data across to NRMN DB:
1. ingesting these additional data as M2 Block2 through the UI 
2. manual SQL ingest
 
Note that for Option 1 to be possible we will have to tweak the ATRC  "survey exist" check that already allows ingest of M3,M4,M5 data separately from M1,M2.

In terms of effort, option (1) will require less work than (2) with the advantage in (1) that the data will be validated  against  current checks.

**Comment by LizziOh** [comment]
If option 1 is less work then that sounds good, if there is a way to ensure they retain the same SurveyID as the existing data in the same survey..?

**Comment by bpasquer** [comment]
The SurveyID will be the same as long as the site-date-depth combo is

**Comment by bpasquer** [comment]
**Next step:**
- identify the observations and survey information (ie survey Notes) to extract from IMAS bio div [Bene]
- extract  [Bene]
- check that no data is missing  [Bene]
- format the data to the data ingest XLSX format [TBD]
- ingest [TBD]
- edit the survey notes of the impacted surveys [TBD]

**Comment by bpasquer** [comment]
Based on the information provided in #689, 623 observations from 92 transects have been extracted from IMASBiodiv using the query in the 'ATRC_AdditionalData_query.txt' file and   and copied in the 'ATRC_AdditionalData_results.csv' .  The file also contains  the mapped site codes.

Could you please have a look and let me know if there is any information (column) I should include or if there is inconsistencies between the extracted data and the source data.

The next step will be to reformat the file into the ingest template format, and prepare SQL scripts to ingest observation related information like:
"Notes"
"Biomass"
"SizeRaw"
"DescriptiveName"
"SizeClassRaw"
"LegalSize"
"SizeEstimated"
"SpeciesSex"
"SimulatedAbsence"
"SizeClassEstimated"

[ATRC_AdditionalData_result.csv](https://github.com/aodn/nrmn-application/files/7748701/ATRC_AdditionalData_result.csv)

[ATRC_AdditionalData_query.txt](https://github.com/aodn/nrmn-application/files/7748702/ATRC_AdditionalData_query.txt)

**Comment by LizziOh** [comment]
Hi Bene, 
I can confirm these surveys are correct data, and all 92 additional M2 are there.  I think the basic data is all we need.  The survey notes "has additional data: M2 B2" could be added as a survey level note, but this would be a separate job I think?

**Comment by bpasquer** [comment]
Hi Lizzie,
Thank you for checking the data.
Yes , updating/adding the survey notes will be done in a bulk update in as a separate job.

So, if I understood you correctly this morning, you said that these data are needed in the database for reporting by the end of January?

cheers,
Bene
________________________________

**Comment by LizziOh** [comment]
Thanks Bene 😊
Yes, Toni thought they were needed for the report our colleagues in SA are working on. But I’m meeting with the James, who is helping write that report, tomorrow at 3pm so I can confirm after that.
Cheers,
Lizzie

**Comment by bpasquer** [comment]
Ok 👍

Cheers,
Bene
________________________________

**Comment by bpasquer** [comment]
SA data have been ingested (2022/03/02)
TAS data need to be checked for 
- inconsistencies in abundances between RLS and NRMN database see https://github.com/aodn/nrmn-application/issues/774 
- potential duplicates with RLS surveys as explained by Lizzie (email 2022/02/23):

> The data from S.A. (“GSV” site codes) are fine to go, as well as data from 2 “TAS” sites.  The other Tassie surveys are all duplicated in NRMN under both programs and we need to decide on a plan.  Things to note about the duplications:
The data under RLS program has both blocks –  i.e. already has the “additional data”, but it is inconsistent whether this is block 1 or 2 that relates to the “additional data” that is missing from the ATRC data
The data under ATRC has M3 in situ data (at least some do but haven’t checked completeness)
The data under RLS has PQs and thus the survey_id is an important to link to the PQs
One more site-date combination has data for both programs in NRMN but they do not match (see attached)
Also, I’ve highlighted some records that are inconsistent between the 2 databases.  This is often repeated for certain species like Forsterygion gymnotum or Pempheris multiradiata, but it tends to be abundance numbers that are different rather than omissions so I’m very confused.  Could you have any idea why this is the case and if so is it a problem more widely in the data?
It may be good to do this in two stages – stage 1 – the SA data which is need by the ATRC collaborators over there soon, and stage 2 the TAS data which is less of a priority.

**Comment by bpasquer** [comment]
Following Lizzie's email (2022-03-05),more fixes have been applied to SA data:
- [x] first: ingest of some more additional data (method 2, block 2) for 2 surveys. This data was never ingested in either database as it was missed in the original data entry spreadsheets for some reason.  I’ve checked the 2 relating surveys in NRMN prod and they indeed are missing M2,B2 data. The only other difference is that they are under the program RLS.
- [x] second: 4 surveys and their corresponding observations need to be deleted from the database: 912353399, 912353400, 912353401, 912353402.   I’ve also confirmed that the data is duplicated with surveys :912347006,912347007,912347018,912351130.  

- [ ] The third task is not urgent, but there is a list of diver names that need to be changed.  Just data entry errors where the wrong initials were entered.  There are a few that need to be checked, so once we fix the first two issues we can check in about the final list of diver changes to be made.  I’ll share the link to the google sheet with the changes needed now anyway.

**Comment by bpasquer** [comment]
Task in regards to divers update is not reqyired anymore.It will be executed by the data officer. See NRMN meeting minutes 2023-06-15. https://www.notion.so/imos-world/Meeting-2023-06-15-f65d06f222594efea1d1ae47ca005249?pvs=4
