### ISSUE TITLE
Exclude non-cryptic fish species from M2 cryptic fish endpoints

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#695]
(from email thread 08 Nov 2021)

the M2 cryptic fish contains non cryptic fish species. 
Most are probably errors  and those that are not could be made M0. That will be fixed when the correctlion tools will be available
In the meantime, these non cryptic species should be excluded from the M2 cryptic fish endpoint ( private and public) .
A list of possible exclusion is attached below:
[Possible exclusions from cryptic fish endpoint.xlsx](https://github.com/aodn/nrmn-application/files/7534987/Possible.exclusions.from.cryptic.fish.endpoint.xlsx)

**Comment by LizziOh** [comment]
related to new issue #711
