### ISSUE TITLE
Review of cryptic fish family list and species whose family is not in cryptic fish family list but whom have observations in method 2.  

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#711]
This issue is related to #697 .

Observations for 160 species are now excluded from the ep_m2_cryptic_fish because their families are not in the cryptic fish family list.  Some of these have been flagged by Rick and Graham as considered cryptic, so their family can be added to the cryptic fish family list.  Others need to be checked as their observations may be errors to be fixed or should be converted to method 0 observations.
[Cryptic fish family list review.xlsx](https://github.com/aodn/nrmn-application/files/7630763/Cryptic.fish.family.list.review.xlsx)

Note from Graham's email: "A lot of these are likely entry miscoding errors, and should be weeded out from the database. On the other hand, anything interesting could be moved to M0 rather than excluded completely."

**Comment by LizziOh** [comment]
Rick and Gedgar have consolidated their suggestions for the cryptic fish families in question, with the decisions:

•	Phycidae – in
•	Berycidae – out
•	Ambassidae – take out (was formerly in)
•	Centriscidae - take out (was formerly in)
•	Aulopidae – take out (was formerly in)
•	Ginglymostomatidae – out
•	Pterelotridae - out
•	Microdesmidae – out
•	Sciaenidae - out

**Comment by LizziOh** [comment]
Testing... I can't seem to find any Phycidae in systest, eg. Phycis phycis from surveys 912349332 and 912349366

**Comment by LizziOh** [comment]
Also, there were some families in the previous file attached confirmed my Gedgar and Rick to add. So please add the following:
(@atcooper1 any thoughts on these?)
- Harpagiferidae
- Latidae
- Pholidichthyidae
- Congiopodidae
- Urotrygonidae
- Trachinidae
- Percophidae
- Anguillidae

**Comment by atcooper1** [comment]
All look good to me!

**Comment by bpasquer** [comment]
OK, no worries, I thought the final decision was the consolidated list you sent 10 days ago.

**Comment by LizziOh** [comment]
Thank you... yes I re-read the email and confirmed that list was for extra changes and the ones needing further discussion.  Rick had also agreed with Gedgar's additions in the file. Cheers!

**Comment by bpasquer** [comment]
>Testing... I can't seem to find any Phycidae in systest, eg. Phycis phycis from surveys 912349332 and 912349366
@LizziOh the updated function ran overnight which fixed the problem. You should be able to find Phycidae in the cryptic endpoints now.

**Comment by bpasquer** [comment]
the change to add the following families  Harpagiferidae, Latidae, Pholidichthyidae,Congiopodidae,Urotrygonidae,Trachinidae,Percophidae, Anguillidae
to the cryptic list  has been deployed to systest.

**Comment by LizziOh** [comment]
From meeting:  Bene to add to the list of extra cryptic observable item name inclusions:

- Actinopterygii spp.
- Elasmobranchii spp.
- Unidentified eel
