### ISSUE TITLE
Direction "O"

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#714]
Can the letter "O" be added to the list of acceptable directions for ingesting data and editing direction of existing surveys in the survey reference list?
This "O" is to signifiy when a survey follows a rounded patch of reef, rather than a straight line in any of the compass directions.  There are many examples of this existing in the database already.

**Comment by bpasquer** [comment]
@LizziOh  "invalid" directions ( i.e. anything that does not contain N,S ,E,W) are excluded from the public endpoint for survey list( ep_survey_list public)
Do you want the public endpoint rule for valid direction to be updated as well?

**Comment by LizziOh** [comment]
I don't think that's necessary and would warrant updating the metadata to explain the meaning.  I'd guess that people mainly use direction to know where on the reef to to re-survey, and hence need the private endpoints with full coordinate resolution.  Any thoughts @atcooper1 ?

**Comment by LizziOh** [comment]
Have tested the fix in systest, and direction "o" passes validation.  Happy for it to go to prod.
