### ISSUE TITLE
Inconsistent information for PQ diver

### ISSUE THREAD

**Issue by LizziOh** [aodn/nrmn-application#739]
In the UI the edit survey view info comes up with a PQ diver Andrew Altieri for survey 7000491, but the view survey is blank for that field, and his name is no where in the survey list endpoint for that survey.  
Is this a widespread issue needing addressing?

**Comment by nspool** [comment]
Since the PQ Diver edit field is not nullable it is defaulting to the first diver in the DB. Until this is fixed it won't be possible to edit a survey that should not have a PQ Diver recorded.

**Comment by LizziOh** [comment]
I have tested this in Systest and it is working now (no error 400).
