### ISSUE TITLE
Mapping RLS with NRMN Species Id for RLS Website

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#749]
From email discussion 20/12/2021(:
Toni
>Currently the RLS website is still pointing to the old DB layers because Sumit is still having trouble matching up the new layers Cam sent through earlier this year. On having a look, it seems that Species ID has changed between layers and all species are displaying with incorrect species name and distributions. When we run the new layers, all the species pages display incorrect species names and distributions.
When we compare the two files from the old and new DB layers:
The Species ID for Jasus edwardsii in the old data layer, is 270, but in new file (new url, new_species.csv) it is 271.

>In the new file, 270 is listed as Agnewia Tritoniformis  and 271 is not present in the old database layer.

 >The old DB file has 3 columns with the same SpeciesID (column 2, 3, 4)

>And the New DB layer has one entry of SpeciesID (Column 2). Currently Sumit is using column 2 to generate the species names/distributions/images which should return the same results.

 >Can you please confirm if SpeciesID has in fact changed? If it has, we will need to look into why and how we can go back to the old SpeciesID’s.

Bene:
>So yes, I can confirm the Species ID changed because it was not a requirement to retain or migrate the old species ID in the new database ( https://github.com/aodn/NRMN/issues/178)
From a quick look I think the discrepancy between species IDs in the old and new endpoints comes from the data cleaning applied during the migration, for example exclusion of species name like "UNUSED" (duplicates and misspellings essentially).

Toni:
>Hi Bene,
Thanks for the info. I just had a look at that issue and it doesn’t mention much about retaining (or not) the species ID during migration, I’m surprised to read that Just didn’t specify this more clearly as it is something that is important and used for the website scripting.
Hopefully it is something that can be resolved easily? 

Bene:
> Following our discussion this morning, we will add a new column to the observable_item_ref table and to the 3 RLS website specific endpoints (ep_species_list,ep_species_survey,ep_species_survey_observation) .

>To populate the new observable_item_ref column, we need to map the new Ids to the old ones.
I have prepared a file with 3 sheets, the first one combiningspecies ID from both NRMN and IMAS database where I  have started the mapping exercise, and the other 2 with the copy of the source data.

>Once the mapping is done we will proceed with the database changes.

**Comment by bpasquer** [comment]
Toni performed the mapping in the following sheet:
[IMAS-NRMN_SpeciesIDmapping.xlsx](https://github.com/aodn/nrmn-application/files/7975634/IMAS-NRMN_SpeciesIDmapping.xlsx)

**Comment by bpasquer** [comment]
Looking at the Species ID mapping  we have:
|                   | IMAS | NRMN |
|-------------------|------|------|
| Number of species | 8199 | 8020 |

The difference in the total number of species is due to:
- the cleaning applied to the source list to remove duplicates and misspelled names during the migration 
- the addition of new species in the NRMN DB
### Problem:
There is more Species in the IMAS DB than in the NRMN even though NRMN has new species (78).
All species need a Mapped ID however ,the newly entered species don't have one.
Because  the max value for Species ID  in IMAS >NRMN, the mapped_ID for the new species cannot be equal to their NRMN SpeciesID (already mapped to a different species) 

### Proposed Solution:
For new species we could adopt either one of these format: 
Mapped_ID = 99900000  + observable_item_id
Mapped_ID = 999 +  observable_item_id/1e4 
Both solutions clearly indicate where the new numbering system starts( if one day the index is dropped ) and keep a reference to the observable item ID which simplifies the incrementation of this new index in the DB.

**Comment by bpasquer** [comment]
Data, python script to generate the SQL query and SQL script provide in https://github.com/aodn/nrmn-application/pull/760 

After the changes are applied to the DB, the next step is update the UI code to generate  the mapped_id for new observable_items @nspool 
At the last catch-up  we agreed  that Solution 1) : Mapped_ID = 99900000 + observable_item_id
is the most appropriate.

**Comment by nspool** [comment]
@bpasquer created a PR to set the mapped_id in a trigger https://github.com/aodn/nrmn-application/pull/761.
