### ISSUE TITLE
Populate taxonomic information for superseded species

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#758]
Just used to delete taxomomic information for superseded species (see https://github.com/aodn/nrmn-application/issues/726#issuecomment-995401952).
As a results about 300 species have no taxonomy and as a results are excluded from the endpoints. (see also 

After discussion at the catch-up meeting on 03/02/22 it's been decided that the taxonomy for these superseded species should be (re)populated. 
Bene will provide the list of species to Toni and Liz. They will to fill up the taxonomic information and a bulk update of the NRMN DB will be run based on this info .

**Comment by bpasquer** [comment]
[Superseded_Species_Missing_Taxonomy.csv](https://github.com/aodn/nrmn-application/files/7998804/Superseded_Species_Missing_Taxonomy.csv)
The list of superseded species missing taxonomic information and the associated superseded_by species information was extracted using the query below . See the file attached.

```sql WITH superseded AS(SELECT observable_item_id,aphia_id,observable_item_name,superseded_by FROM nrmn.observable_item_ref WHERE 
phylum IS NULL AND "class" IS NULL AND "order" IS NULL AND "family" IS NULL
EXCEPT
SELECT observable_item_id,aphia_id,observable_item_name,superseded_by FROM nrmn.observable_item_ref
WHERE observable_item_ref.obs_item_type_id in(5,6)),
taxo AS (SELECT observable_item_id,observable_item_name, phylum,"class","order","family" FROM nrmn.observable_item_ref)

SELECT sup.observable_item_id,sup.observable_item_name,sup.aphia_id,sup.superseded_by,taxo.phylum,taxo.class,taxo.order,taxo.family FROM superseded sup
LEFT JOIN taxo ON taxo.observable_item_name=sup.superseded_by
```

@atcooper1 @LizziOh, could you please confirm the information I extracted is correct  and I 'll prepare the script to bulk update the database

**Comment by bpasquer** [comment]
The impact of the missing taxonomy of the species on the endpoint was mainly limited to M@ endpoint ( M1 has no taxonomic condition, is is based on the survey method).
Having the taxonomy set for the superseded species will add this estimated number of observations to the M2 endpoints:
``` sql 
select count(*) from nrmn.observation 
join nrmn.survey_method ON survey_method.survey_method_id = observation.survey_method_id
join nrmn.observable_item_ref ON observable_item_ref.observable_item_id = observation.observable_item_id  
where method_id =2 and observation.observable_item_id in (4193,
2682,2697,2684,2702,4179,4780,4182,4117,2787,2783,5048,2789,4876,4783,4133,1304,4136,4148,825,4110,5276,6777,4792,4758,2780,5272,4121,2782,4935,4016,2688,4778,
4933,942,2698,4099,765,5230,2993,2786,2779,3118,4197,2680,4773,4153,4111,4195,4125,4114,4782,5061,4141,757,2785,2797,5131,4957,4958,2701,4007,4869,832,2685,4122,5217,4936,4113,
4879,4096,4118,750,4364,4767,5187,2681,4116,4100,4766,4791,4134,4818,2788,1043,5274,4014,6763,4788,2784,4890,1192,5043,5195,4143,4124,4955,4198,4140,4106,4135,4369,2781,4188,
4189,4149,4785,2994,4156,5133,4191,2996,2677,2696,5123,4115,4123,4770,4769,5269,4200,4798,2676,4147,4789,2995,4152,4011,5085,1087,4109,2687,4837,5129,5169,7715,6570,6615,4747,6771,6770,4112,4768,5702,4108,4765,4104,3014,4755,5122,4775,5703,4797,1251,4938,837,838,3135,4025,4761,4343,4772,3016,4756,4757,4810,3004,2678,3005,4026,4762,
3132,5308,3129,1256,4779,4216,4017,4787,3008,4759,4018,2679,4102,4013,3003,4748,2997,3015,4184,4795,2683,4030,4101,4154,4127,939,4132,945,4107,4870,1224,3012,4934,3013,3048,4120,
2686,4126,4790,4029,972,4781,1152,4151,4097,4753,4020,4008,4138,4012,4763,4145,4760,2999,4774,4752,1025,4150,4021,1222,4146,4009,4796,3010,3011,904,1058,5206,
4130,3113,5081,3007,4754,3128,3127,3126,3122,3137,4137,3009,4019,6769,4129,4749,2693,1281,5124,1125,2998,2689,4023,3002,4010,1286,4131,4105,4095,5313,4764,4103,
844,4098,1123,4128,4028,4142,1288,4144,4015,4093,3114,3000,3115,4119,4022,5125,4777,4751,5094,4139,4794,2699,2700,4750,1016,4885,4784,5729,4771,1179,6767) 
```  
| count |
| ------- |
| 1787 |

**Comment by LizziOh** [comment]
I can confirm that the list of superseded species, and their matched taxonomic classification is good.  I did a cross check with a worms match tool and all seem to match at the level of inclusion in the extracts. In the file attached, there are a few species for us to check whether to update (either revert to accepted (red highlighted), or check the superseding (green highlighted).

[Superseded_Species_Missing_Taxonomy.xlsx](https://github.com/aodn/nrmn-application/files/8085485/Superseded_Species_Missing_Taxonomy.xlsx)

**Comment by bpasquer** [comment]
@LizziOh, @atcooper1, I created a new label "Data officer" to tag issues that need to be followed up by either one of you(or both)
