### ISSUE TITLE
UI loading hundreds of "NOT PRESENT" rows of data from template into staged data

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#943]
UI seems to be loading hundreds of "NOT PRESENT" rows of data from template into staged data. This was fixed about a year ago where by the UI would cut duplicated (more than 3 identical rows) or duplicated NOT PRESENT rows of redundant data from the ingested templates, however it seems to be loading these again?

**Comment by nspool** [comment]
Hi Toni, could you please send me an example? Rows at the end of the sheet should still be skipped if all columns are the same except for measurements and row ID.

**Comment by atcooper1** [comment]
@nspool try this file in staged: 
RLS NSW_PS17_FlyPoint_CAS_CS6February2022_t.xlsx 
This is the example where Debris zero is the last row of valid data, and the second duplicated row needs to be cut.

**Comment by nspool** [comment]
@atcooper1 The species code is empty in row 158, but is 0 in row 159. The duplicate detection is only removing row 159 onwards. Should the species code be ignored when checking for duplicate rows?

**Comment by LizziOh** [comment]
tested (job #65 in systest).  Working
